Update config
eslint/eslint pull request #13677
Opened 2020-09-09 17:26 UTC by khawarlatifkhan

#### Prerequisites checklist

- [ X ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ X ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Updated link to babel-ESLint

#### Is there anything you'd like reviewers to focus on?
N/A

2020-09-09 17:31 UTC, anikethsaha approved these changes

2020-09-09 17:33 UTC, anikethsaha requested changes
Commit message is not formatted as per the rule. 

try `Docs: fixed babel eslint name in configuration guide`

2020-09-10 14:08 UTC, kaicataldo approved these changes

2020-09-10 14:09 UTC, merged

2020-09-10 14:09 UTC, kaicataldo commented
Thanks for contributing!