Fix: --cache ignores file mtime in CI environments
eslint/eslint pull request #13713
Opened 2020-09-23 21:40 UTC by wmhilton

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

The internal caching behavior defaults to checksums instead of mtime-based when running in CI environments.

#### Is there anything you'd like reviewers to focus on?

There have been previous attempts to address this, however it [got hung up](https://github.com/eslint/eslint/pull/11487#issuecomment-546095631) because we [didn't want to add a command line flag](https://github.com/eslint/eslint/pull/11487#issuecomment-470739742) or a new environment variable to control the behavior as that would alter the public-facing API and make the internals of how `eslint` caching works part of the public API.

This PR attempts to side-step that by not exposing the behavior, merely changing the default if `process.env.CI` is set (which it generally is in CI environments).

If there are objections to relying on the `process.env.CI` environment variable, I suggest that - performance allowing - we simply always using the more robust caching strategy.

#### background

Currently CI users resort to hacks such as manually modifying the `mtime` of all their files:
https://github.com/salto-io/salto/pull/395/files#diff-5d8151d7fb61e762279563e3d38abd41R1-R17

Previous attempts to address this:
- https://github.com/eslint/eslint/issues/11319
- https://github.com/eslint/eslint/pull/11487
- https://github.com/eslint/eslint/issues/11490
- https://github.com/royriojas/file-entry-cache/pull/14

2020-09-24 00:47 UTC, nzakas commented
Thanks for attempting this. I’m not comfortable with reading an environment variable for this purpose — that’s just one assumption too many when determining how ESLint should behave.

We did recently merge this RFC that covers this use case: https://github.com/eslint/rfcs/pull/63

2020-09-24 03:03 UTC, wmhilton commented
Oh that's fantastic! That's great. Is there already an implementation of RFC 63? If not, I can pivot to implementing it.

2020-09-24 17:46 UTC, wmhilton commented
@c-home anything I can do to help?

2020-09-24 20:06 UTC, nzakas commented
I don't believe implementation has started yet, so you can feel free!

2020-09-25 02:35 UTC, c-home commented
> @c-home anything I can do to help?

Hi, I started implementing the RFC but haven't gotten a chance to add testing yet.
If you would like to implement it that is great :)

2020-10-07 17:53 UTC, nzakas requested changes
Sorry for the delay in reviewing, this looks really good. Just a few small things to clean up and I'd like to get a few other sets of eyes on this, too.

2020-10-07 17:53 UTC, nzakas commented on docs/user-guide/command-line-interface.md
> +Strategy to use for detecting changed files. Can be either `metadata` or `content`. If no strategy is specified, `metadata` will be used.
```suggestion
Strategy for the cache to use for detecting changed files. Can be either `metadata` or `content`. If no strategy is specified, `metadata` will be used.
```

2020-10-07 17:53 UTC, nzakas commented on lib/eslint/eslint.js
> + * @property {"metadata" | "content"} [cacheStrategy] The strategy used to detect changed files.
This file shouldn't have any Node.js-specific information inside of it. It doesn't directly access the cache, so I think we can safely remove all of the cache-related changes from this file.

2020-10-07 17:53 UTC, nzakas commented on lib/options.js
> +            description: "Strategy to use for detecting changed files"
```suggestion
            description: "Strategy to use for detecting changed files in the cache"
```

2020-10-07 17:53 UTC, nzakas commented
@c-home if you have the time to take a look at this implementation, we'd appreciate your feedback.

2020-10-08 06:28 UTC, c-home commented
> @c-home if you have the time to take a look at this implementation, we'd appreciate your feedback.

Had a quick look and it looks great. Will have a closer look soon. Thank you for implementing this wmhilton.

2020-10-08 23:36 UTC, c-home commented on lib/cli-engine/lint-result-cache.js
> +            fileDescriptor.meta.hashOfConfig !== hashOfConfig;
Will `changed` be `true` if the `cacheStrategy` changes? Related to [this issue](https://github.com/eslint/rfcs/pull/63#issuecomment-676463622) raised in the rfc.

2020-10-11 08:19 UTC, c-home commented
For users of eslint cache, this is something to consider - https://github.com/eslint/rfcs/pull/68.

2020-10-13 00:38 UTC, nzakas commented on lib/eslint/eslint.js
> + * @property {"metadata" | "content"} [cacheStrategy] The strategy used to detect changed files.
Oops, please ignore this comment. I misread the filename. This looks good. :+1:

2020-10-29 14:58 UTC, wmhilton commented
Ugh. As pointed out in [this comment](https://github.com/eslint/rfcs/pull/68#issuecomment-707414470) some very notable rulesets such as `@typescript-eslint` are incompatible with `--cache` by design. That really puts a damper on my enthusiasm for this, since anything less than 100% reproducible isn't good for our CI use case at Stoplight. :-(

2020-10-29 20:06 UTC, nzakas commented
It seems like you are pretty close to finishing this, and this is something we plan on doing regardless. Do you want to finish it up so we can merge it?

We do still need to solve for the case where plugins are doing unexpected things, but there are plenty of folks who would benefit from this PR in the meantime.

2020-11-08 10:47 UTC, royriojas commented
hi @nzakas @wmhilton I've published a new version of `file-entry-cache`. Version `6.0.0`. This version has no new functionality but updates the dependencies to latest to remove security warnings.

It is a major upgrade to avoid any potential issues since I've aligned the supported node versions with the ones `eslint` is currently using.

2020-11-11 19:28 UTC, nzakas commented
@royriojas thanks for the heads up. Can you open an issue so that info doesn’t get lost here?

2021-02-07 11:34 UTC, vaniyokk commented
Any update on this?

2021-02-09 01:46 UTC, nzakas commented
@vaniyokk it appears this has been abandoned. Do you want to take it up?

2021-02-09 03:40 UTC, kirill-konshin commented
> @vaniyokk it appears this has been abandoned. Do you want to take it up?

This is quite sad. In our case on CI with repo having around 10K modules ESLint takes waaaay too much time, since the cache is not used at all between pushes (due to timestamps inconsistency, Git does not maintain them, and GitLab does not have workspaces so far).

2021-02-09 07:08 UTC, royriojas commented
The merge request seems to be almost ready, isn't it? @nzakas. I think it is only a matter of fix the tests

2021-02-09 08:10 UTC, snitin315 commented
Can I work on this and finish the PR ???

2021-02-09 18:48 UTC, nzakas commented
@royriojas yes, it looks basically done at this point.

@snitin315 yes, you can definitely take it over. You should be able to pull the branch from where this PR was created and then create a new PR with that code. When you do, just comment here with the new PR number so we can close this and move our focus over to the new PR. Thanks!

2021-02-18 11:46 UTC, mdjermanovic commented
Closing as there's a new PR #14119

2021-02-18 11:46 UTC, closed without merging