Fix: support async arrow functions in `function-paren-newline`
eslint/eslint pull request #13729
Opened 2020-10-01 23:27 UTC by mdziekon

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Bug fix (#13728)

#### What changes did you make? (Give an overview)

Added support for the `async` ArrowFunctionExpression in `function-paren-newline`. This fixes the issue where source analysis for this node type wrongly assumes that it does not have an opening parenthesis (because it thinks that in this case, opening paren is always the first token, which since ES2017 is no longer a guarantee).

#### Is there anything you'd like reviewers to focus on?

No

2020-10-02 09:00 UTC, mdjermanovic requested changes
@mdziekon thanks for finding and fixing this bug!

The code and very comprehensive tests look great.

I have just a small request about the commit message. Since this is a bug fix that can produce more warnings, the commit message should start with `Update:` instead of `Fix:` (this is important for our [semver policy](https://github.com/eslint/eslint#semantic-versioning-policy)).

The message could be something like this:

```
Update: support async arrow fn in function-paren-newline (fixes #13728)
```

2020-10-02 10:52 UTC, mdziekon commented
@mdjermanovic sure thing, I've pushed an amended commit message.

2020-10-02 11:11 UTC, mdjermanovic approved these changes
LGTM, thanks!

2020-10-04 06:14 UTC, yeonjuan approved these changes
LTGM! Thanks

2020-10-06 13:03 UTC, merged

2020-10-06 13:03 UTC, mdjermanovic commented
Thanks for contributing!