Update: eslint --env-info ouput os info
eslint/eslint pull request #14059
Opened 2021-02-02 03:24 UTC by aladdin-add

#### Prerequisites checklist

- [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
`eslint --env-info` print the os info, it looks like:
```bash
Environment Info:

Node version: v15.5.0
npm version: v7.3.0
Local ESLint version: v7.19.0 (Currently used)
Global ESLint version: Not found
Operating System: macOS Big Sur
```

#### Is there anything you'd like reviewers to focus on?

it seems hard to test all the os platforms (and it should have been the scope of `os-name` package).
to make the tests passed, I just assigned the `os.platform()` and `os.release()`.

2021-03-09 01:51 UTC, nzakas commented
I’m not sure it’s worth adding another dependency just to output debug information. Couldn’t we just use process.platform?

2021-03-09 02:34 UTC, aladdin-add commented
the package can output more readable info, e.g.
```js
osName('win32', '6.3.9600');
//=> 'Windows 8.1'
```

I think either is fine. will remove the dependency if you prefer that way. :)

2021-03-10 01:28 UTC, nzakas commented
As I said, I just don’t think this is important enough to add another dependency. Win32 or Win64 is plenty of info for our purposes.

2021-03-10 06:00 UTC, aladdin-add commented
just rebased the latest master.

2021-03-11 01:41 UTC, nzakas approved these changes
LGTM

2021-03-11 17:04 UTC, mdjermanovic commented
I think we can already mark this as accepted, since it matches our new bug report template.

2021-03-11 17:08 UTC, mdjermanovic requested changes

2021-03-11 17:08 UTC, mdjermanovic commented on tests/lib/shared/runtime-info.js
> +            os.release = () => "20.3.0";
Can we use `sinon` here to prevent this change from leaking to other tests?

2021-03-17 00:39 UTC, nzakas approved these changes

2021-03-20 12:04 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-03-20 12:06 UTC, merged