Fix: handle logical assignment in no-self-assign
eslint/eslint pull request #14152
Opened 2021-03-01 14:32 UTC by Zzzen

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**
no-self-assign

**Does this change cause the rule to produce more or fewer warnings?**
more warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
new default behavior

**Please provide some example code that this change will affect:**

```js
a &= a;  
a |= a;
a &&= a;
a ||= a;
a ??= a;
```

**What does the rule currently do for this code?**
no errors are reported

**What will the rule do after it's changed?**
all lines will be reported.

#### What changes did you make? (Give an overview)
currently, only `=` is handled in `no-self-assign`. But other logical assignment operators work roughly the same as `=`.

`a &&= a` is `a && (a = a)`, which is essentially a noop.

#### Is there anything you'd like reviewers to focus on?

2021-03-01 15:59 UTC, mdjermanovic commented
Hi @Zzzen, thanks for the PR!

We listed adding support for `&&=`, `||=`, and `??=` operators to the `no-self-assign` rule as _maybe_ in https://github.com/eslint/eslint/issues/13569. We're not yet sure if that change makes sense, so I marked this as "evaluating".

As for `&=` and `|=`, I think that's different as it involves a calculation before the assignment, and it doesn't have to be a noop (should be for integers, but e.g, `1.5 | 1.5` is `1`, `null | null` is `0`, etc.), so those checks probably don't belong to `no-self-assign`.

2021-03-02 06:11 UTC, Zzzen commented
Ooops, did not notice the issue. IMO, even though `|=` may have side effects on non-integers, `a |= a` is likely a typo and should be disallowed like how object properties are handled.

2021-12-26 16:28 UTC, mdjermanovic commented
@eslint/eslint-tsc thoughts about this proposal for the `no-self-assign` rule?

* Should it report `a &&= a`, `a ||= a`, and `a ??= a`? I think this makes sense since these are essentially the same as `a = a`.
* Should it report `a &= a`, and `a |= a`? I think this doesn't belong to this rule, for the reasons described in [this comment](https://github.com/eslint/eslint/pull/14152#issuecomment-788062375).

2021-12-28 00:48 UTC, nzakas commented
@mdjermanovic i agree with your reasoning.

2021-12-28 23:54 UTC, btmills commented
@mdjermanovic I agree as well.

2021-12-29 10:50 UTC, mdjermanovic requested changes
@Zzzen sorry for the delay, the change for `&&=`, `||=`, and `??=` is accepted now.

Can you also update the documentation for this rule?

2021-12-29 10:50 UTC, mdjermanovic commented on lib/rules/no-self-assign.js
> +                if (["=", "&=", "|=", "&&=", "||=", "??="].includes(node.operator)) {
```suggestion
                if (["=", "&&=", "||=", "??="].includes(node.operator)) {
```

2021-12-29 10:50 UTC, mdjermanovic commented on tests/lib/rules/no-self-assign.js
> +        },
```suggestion
```

It would be nice to also add `"a &= a"` and `"a |= a"` to `valid` test cases.

2021-12-30 05:01 UTC, Zzzen commented
👌  updated

2021-12-30 13:38 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-12-30 13:39 UTC, merged