Update: add an option to ignore non declaration (refs #12545)
eslint/eslint pull request #14185
Opened 2021-03-06 02:13 UTC by t-mangoe

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#12545 

#### What changes did you make? (Give an overview)
I added an option, `ignoreNonDeclaration`.
This option ignores multi-assign when the variable is being declared.

#### Is there anything you'd like reviewers to focus on?
Nothing in particular.

2021-03-08 16:24 UTC, mdjermanovic requested changes
Hi @t-mangoe, thanks for the PR!

Can you also update [documentation](https://github.com/eslint/eslint/blob/master/docs/rules/no-multi-assign.md) for this rule?

2021-03-13 00:10 UTC, t-mangoe commented
@mdjermanovic 
Thank you for your comment!!
I will update the documentation.

2021-03-20 01:37 UTC, t-mangoe commented
> Hi @t-mangoe, thanks for the PR!
> 
> Can you also update [documentation](https://github.com/eslint/eslint/blob/master/docs/rules/no-multi-assign.md) for this rule?

I have updated the documentation.
If you have time, please check out my changes.

2021-03-22 01:04 UTC, mdjermanovic requested changes
Thanks! The code looks good, I left only a minor suggestion, and a few comments about the documentation and the tests.

2021-03-27 00:58 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +* `"ignoreNonDeclaration": false` (default) disallows using multiple assignments to already declared variables.
I fixed the explanation as above.

2021-03-27 00:58 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +Examples of **correct** code for the `{ "ignoreNonDeclaration": true }` option:
I fixed the code as above.

2021-03-27 00:59 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +x.one = y.one = 1; // this is allowed.
I fixed the code as above.

2021-03-27 01:00 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +```
I added one correct example and one incorrect example.

2021-03-27 01:02 UTC, t-mangoe commented on tests/lib/rules/no-multi-assign.js
> +const options = [{ ignoreNonDeclaration: true }];
I removed the `options` variable and wrote option value directly in test cases.

2021-03-27 01:03 UTC, t-mangoe commented on tests/lib/rules/no-multi-assign.js
> +        { code: "const x = {};const y = {};x.one = y.one = 1;", options, parserOptions: { ecmaVersion: 6 } }
I added the valid test case.

2021-03-27 01:03 UTC, t-mangoe commented on tests/lib/rules/no-multi-assign.js
> +
I added the above three test cases.

2021-03-27 01:05 UTC, t-mangoe commented on lib/rules/no-multi-assign.js
> +                const target = options.ignoreNonDeclaration ? ["VariableDeclarator"] : ["AssignmentExpression", "VariableDeclarator"];
I moved the variable up, and renamed to `targetParent`.

2021-03-27 01:10 UTC, t-mangoe commented
@mdjermanovic 
Thank you for your suggestion!
I reflected your comments. If you have time, please confirm my modification.

2021-04-02 21:06 UTC, mdjermanovic requested changes
Thanks for the changes! I have just two minor suggestions, and then LGTM.

2021-04-03 08:28 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +/*eslint no-multi-assign: ["error", { ignoreNonDeclaration: true }]*/
I added the quotes.

2021-04-03 08:28 UTC, t-mangoe commented on docs/rules/no-multi-assign.md
> +/*eslint no-multi-assign: ["error", { ignoreNonDeclaration: true }]*/
I added the quotes.

2021-04-03 08:29 UTC, t-mangoe commented
@mdjermanovic 
Thank you for comments! I fixed the doc and reflected your comments.

2021-04-03 21:18 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-04-03 21:22 UTC, mdjermanovic commented
I'm not sure what's happening with the CLA check, will close/reopen to see if it will fix the check.

2021-04-03 21:29 UTC, mdjermanovic commented
All checks are green now. Thanks for contributing!

2021-04-03 21:30 UTC, merged