Fix: require-atomic-updates false positives in loops (fixes #14208)
eslint/eslint pull request #14282
Opened 2021-03-31 17:12 UTC by patriscus

#### Prerequisites checklist

- [ x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

fixes #14208

Fixes false positives like:
```js
async function foo(e) {
}

async function run() {
  const input = [];
  const props = [];

  for(const entry of input) {
    const prop = props.find(a => a.id === entry.id) || null;
    await foo(entry);
  }

  // false positive:
  // Possible race condition: `const entry` might be reassigned based on an outdated value of `const entry`
  for(const entry of input) {
    const prop = props.find(a => a.id === entry.id) || null;
  }

  for(const entry2 of input) {
    const prop = props.find(a => a.id === entry2.id) || null;
  }
}
```

#### What changes did you make? (Give an overview)

I adapted the `if` condition surrounding the code block that is pushing/setting a reference to the `assignmentReferences` map. This map is subsequently used to get `references` and check for outdated identifier names.

I moved the `isLocalVariableWithoutEscape` in said `if` condition out to a separate variable and extended it with: 
```js
const isVariableDeclaration = isLocalVariableWithoutEscape(variable, isMemberAccess) ||
    node.parent.type === "VariableDeclarator";
```

Since the condition had a comment with  "exclude variable declarations", I removed it and expressed it with the `isVariableDeclaration` variable name.

#### Is there anything you'd like reviewers to focus on?

This is the first time contributing to ESLint (or open-source that is). Please focus on edge-cases or other implications since I do not have the complete context. I'm happy to hear about your concerns and improvement points.

2021-04-08 16:17 UTC, mdjermanovic requested changes
@patriscus thanks for the PR! I think that this solution does fix #14208, but not all similar cases, and maybe it wouldn't be too difficult to fix the actual root cause.

2021-04-09 06:26 UTC, patriscus commented on lib/rules/require-atomic-updates.js
> +                    !isVariableDeclaration
Thanks for the review and the tip! I'll try to get to it in the upcoming week and will give an update latest next weekend

2021-04-10 17:42 UTC, patriscus commented
@mdjermanovic I had some spare time and changed the code such that `segmentInfo` stores references to variables instead of storing variable names. Feel free to review & leave suggestions again. Thanks!

2021-04-17 02:45 UTC, mdjermanovic requested changes
The change looks good, we should just skip unresolved references in `function createReferenceMap`.

`reference.resolved` is `null` if it's unresolved, so this would be a false positive:

```js
/* eslint require-atomic-updates: error */

async function run() {
    await a;
    b = 1; // false positive
}
```

(because we're now tracking undefined variables `a` and `b` as the same `null` variable object in `SegmentInfo`).

That would miss reporting some cases with the same variable name, but it's fine, most of the core rules are ignoring undefined variables.

2021-04-23 17:54 UTC, patriscus commented
I'll get to this PR hopefully this weekend, latest next weekend

2021-05-01 14:17 UTC, patriscus commented
@mdjermanovic I have now updated the code to skip unresolved references. Please let me know if you have further suggestions.

2021-05-03 23:08 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-05-04 05:20 UTC, patriscus commented
Thanks for guiding me through this PR! Much appreciated

2021-05-08 00:54 UTC, btmills approved these changes
LGTM. Congrats on your first open source PR, @patriscus! This will go out in tonight's release.

2021-05-08 00:54 UTC, merged