Mention workaround for the regex escape character
eslint/eslint pull request #14675
Opened 2021-06-05 17:39 UTC by AriaMinaei

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update

#### What changes did you make? (Give an overview)

A small documentation change to mention the workaround for the esquery issue that prevents the forward-slash character to be escaped in regular expressions, when used in `no-restricted-syntax`.

2021-06-07 10:13 UTC, aladdin-add reviewed
can this be fixed the the package?

2021-06-08 18:06 UTC, AriaMinaei commented
Not sure, because the relevant [bug](https://github.com/estools/esquery/issues/68) has been unresolved for a couple of years already.

2021-06-12 00:59 UTC, nzakas approved these changes
LGTM. Thanks

2021-06-12 09:16 UTC, mdjermanovic requested changes

2021-06-12 09:16 UTC, mdjermanovic commented on docs/developer-guide/selectors.md
> +Due to a [bug](https://github.com/estools/esquery/issues/68) in [esquery](https://github.com/estools/esquery), regular expressions that contain a forward-slash character `/` aren't porperly parsed, s
```suggestion
Due to a [bug](https://github.com/estools/esquery/issues/68) in [esquery](https://github.com/estools/esquery), regular expressions that contain a forward-slash character `/` aren't properly parsed, so `[value=/some\/path/]` will be a syntax error. As a [workaround](https://github.com/estools/esquery/issues/68), you can replace the `/` character with its unicode counterpart, like so: `[value=/some\\u002Fpath/]`.
```

2021-06-12 09:33 UTC, mdjermanovic commented on docs/developer-guide/selectors.md
> +Due to a [bug](https://github.com/estools/esquery/issues/68) in [esquery](https://github.com/estools/esquery), regular expressions that contain a forward-slash character `/` aren't porperly parsed, s
`\\` in `[value=/some\\u002Fpath/]` might be confusing. Selector itself should have only one `\`, while the other `\` is required only if the selector is represented in a string literal?

2021-06-12 10:04 UTC, mdjermanovic commented on docs/developer-guide/selectors.md
> +Due to a [bug](https://github.com/estools/esquery/issues/68) in [esquery](https://github.com/estools/esquery), regular expressions that contain a forward-slash character `/` aren't porperly parsed, s
I'd suggest only `\` here (like it is in `[value=/some\/path/]`), and an example that disallows import from `foo/bar`:

```json
{
  "rules": {
    "no-restricted-syntax": ["error", "ImportDeclaration[source.value=/foo\\u002Fbar/]"]
  }
}
```

2021-08-05 00:21 UTC, nzakas commented
I think this is close enough to merge. We can make other tweaks later.

2021-08-05 00:21 UTC, merged