Update: added ignoreExpressions option to max-classes-per-file
eslint/eslint pull request #15000
Opened 2021-08-31 02:43 UTC by JoshuaKGoldberg

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Allowed `max-classes` to take in an object for its options, with a new `ignoreExpressions` option alongside the existing `maxClasses`.

#### Is there anything you'd like reviewers to focus on?

These files are a few years old. Would you like me to update them to a newer format?

2021-09-01 00:41 UTC, nzakas requested changes
The docs specified the option name as “maximum” while the code used “maxClasses”. I think we can just go with “max”, which is what other rules use in a similar situation.

code looks good overall.

2021-09-01 00:41 UTC, nzakas commented on docs/rules/max-classes-per-file.md
> +-   `maximum`: a numeric option (defaulted to 1) to specify the maximum number of classes.
We generally use “max” for this purpose in other rules, so good to be consistent. 

```suggestion
-   `max`: a numeric option (defaulted to 1) to specify the maximum number of classes.
```

2021-09-01 00:41 UTC, nzakas commented on docs/rules/max-classes-per-file.md
> +This rule may take in either an object or a number.
```suggestion
This rule may be configured with either an object or a number.
```

2021-09-01 00:41 UTC, nzakas commented on docs/rules/max-classes-per-file.md
> +        { "ignoreExpressions": true, "maximum": 2 }
```suggestion
        { "ignoreExpressions": true, "max": 2 }
```

2021-09-01 00:41 UTC, nzakas commented on docs/rules/max-classes-per-file.md
> +Examples of **correct** code for this rule with the `maximum` option set to `2`:
```suggestion
Examples of **correct** code for this rule with the `max` option set to `2`:
```

2021-09-01 00:41 UTC, nzakas commented on lib/rules/max-classes-per-file.js
> +                            maxClasses: {
```suggestion
                            max: {
```

2021-09-01 00:41 UTC, nzakas commented on lib/rules/max-classes-per-file.js
> +        const [ignoreExpressions, maxClasses] = typeof option === "number"
```suggestion
        const [ignoreExpressions, max] = typeof option === "number"
```

2021-09-01 00:41 UTC, nzakas commented on lib/rules/max-classes-per-file.js
> +            : [option.ignoreExpressions, option.maxClasses || 1];
```suggestion
            : [option.ignoreExpressions, option.max || 1];
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ maxClasses: 1 }]
```suggestion
            options: [{ max: 1 }]
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ maxClasses: 2 }]
```suggestion
            options: [{ max: 2 }]
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ ignoreExpressions: true, maxClasses: 1 }]
```suggestion
            options: [{ ignoreExpressions: true, max: 1 }]
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ ignoreExpressions: true, maxClasses: 2 }]
```suggestion
            options: [{ ignoreExpressions: true, max: 2 }]
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ ignoreExpressions: true, maxClasses: 1 }],
```suggestion
            options: [{ ignoreExpressions: true, max: 1 }],
```

2021-09-01 00:41 UTC, nzakas commented on tests/lib/rules/max-classes-per-file.js
> +            options: [{ ignoreExpressions: true, maxClasses: 2 }],
```suggestion
            options: [{ ignoreExpressions: true, max: 2 }],
```

2021-09-02 00:47 UTC, nzakas approved these changes
LGTM. Thanks!

2021-09-03 11:15 UTC, snitin315 approved these changes
LGTM, thanks for contributing!

2021-09-03 14:24 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-09-04 00:17 UTC, merged