Update: update options in class-methods-use (refs #14857)
eslint/eslint pull request #15018
Opened 2021-09-01 14:09 UTC by yeonjuan

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

1. add `enforceForClassFields` options.

 - https://github.com/eslint/eslint/pull/14591#discussion_r656613541

2.Fix `exceptMethods` options to use `#` prefix for ignoring private methods 

 - https://github.com/eslint/eslint/pull/14591#issuecomment-866383434

3, fix false-negative

 - https://github.com/eslint/eslint/pull/14591#issuecomment-877815299

```
/* eslint class-methods-use-this: ["error"] */

class C {
    doesNotUseThis() { // false negative
        return class { foo = this };
    }
}
```

#### Is there anything you'd like reviewers to focus on?

2021-09-03 12:14 UTC, mdjermanovic requested changes

2021-09-03 12:14 UTC, mdjermanovic commented on lib/rules/class-methods-use-this.js
> +            "PropertyDefinition:exit": () => stack.pop(),
`this` inside initializer expressions is an instance of the class (or the class itself if the field is static), but `this` inside `[]` is that of the enclosing function.

```js
/* eslint class-methods-use-this: "error" */

class C {
  doesUseThis() { // false positive
    return class { [this.foo] = 1; };
  }
}
```

2021-09-04 16:02 UTC, yeonjuan commented
@mdjermanovic  Thanks for the review :) I changed it

2021-09-04 16:38 UTC, mdjermanovic commented on lib/rules/class-methods-use-this.js
> +            "PropertyDefinition > *.key:exit": pushContext,
```suggestion
            "PropertyDefinition > *.key:exit": pushContext,
            "PropertyDefinition:exit": popContext,
```

`PropertyDefinition: pushContext` - `"PropertyDefinition > *.key": popContext` pair seems unnecessary?

2021-09-05 16:09 UTC, mdjermanovic commented on docs/rules/class-methods-use-this.md
> +/*eslint class-methods-use-this: ["error", {"enforceForClassFields": true }] */
```suggestion
/*eslint class-methods-use-this: ["error", { "enforceForClassFields": true }] */
```

2021-09-05 16:09 UTC, mdjermanovic commented on docs/rules/class-methods-use-this.md
> +/*eslint class-methods-use-this: ["error", {"enforceForClassFields": false }] */
```suggestion
/*eslint class-methods-use-this: ["error", { "enforceForClassFields": false }] */
```

2021-09-05 16:09 UTC, mdjermanovic commented
Code looks good! I left only some suggestions about the documentation.

2021-09-05 17:03 UTC, yeonjuan commented
@mdjermanovic Thanks for the suggestions. I edited and also changed the example order -  https://github.com/eslint/eslint/pull/15018#discussion_r702443876

2021-09-05 17:27 UTC, mdjermanovic approved these changes
LGTM, thanks!

2021-09-05 17:35 UTC, mdjermanovic commented
Also thanks for fixing the behavior of `"exceptMethods"` with numeric and string literals as property names.

2021-09-10 00:30 UTC, nzakas approved these changes

2021-09-10 10:14 UTC, merged