feat: update brace-style for class static blocks
eslint/eslint pull request #15322
Opened 2021-11-16 14:51 UTC by mdjermanovic

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Refs #15016, fixes `brace-style`.

#### What changes did you make? (Give an overview)

Updated the `brace-style` rule to apply to braces of class static blocks.

#### Is there anything you'd like reviewers to focus on?

2021-11-17 01:29 UTC, nzakas requested changes
Left a couple of comments — some of the fixes look broken to me. If this is expected, can you add some comments around the invalid tests explaining why?

2021-11-17 01:29 UTC, nzakas commented on tests/lib/rules/brace-style.js
> +                foo;
Shouldn’t this be indented more?

2021-11-17 01:29 UTC, nzakas commented on tests/lib/rules/brace-style.js
> +                foo;
Same here. This doesn’t properly indented.

2021-11-17 13:09 UTC, mdjermanovic commented
> Left a couple of comments — some of the fixes look broken to me. If this is expected, can you add some comments around the invalid tests explaining why?

I added a comment explaining this. Indentation is expected to be fixed by the `indent` rule in subsequent iterations. The behavior for static blocks is the same as for other blocks:

* [brace-style example with a method](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGJyYWNlLXN0eWxlOiBbXCJlcnJvclwiLCBcIjF0YnNcIl0gKi9cblxuY2xhc3MgQyB7XG4gICAgbWV0aG9kKCkgeyBmb287IH1cbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).
* [brace-style + indent example with a method](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGJyYWNlLXN0eWxlOiBbXCJlcnJvclwiLCBcIjF0YnNcIl0gKi9cbi8qIGVzbGludCBpbmRlbnQ6IFtcImVycm9yXCIsIDRdICovXG5cbmNsYXNzIEMge1xuICAgIG1ldGhvZCgpIHsgZm9vOyB9XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==).

2021-11-18 01:17 UTC, nzakas approved these changes
Thanks!

2021-11-19 10:47 UTC, merged