fix: Avoid dirname for built-in configs.
eslint/eslint pull request #15616
Opened 2022-02-16 22:29 UTC by daidodo

Load eslint:recommended and eslint:all configs via import instead file paths.

Fixes: #15575

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
- [ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
- [ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
- [ ] Add autofix to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [x] Other, please explain: Avoid using `__dirname` for built-in configs, i.e. `eslint:recommended` and `eslint:all`.

#### What changes did you make? (Give an overview)

I made changes to *cli-engine.js* and *file-enumerator.js* to pass in callbacks for getting built-in configs instead of file paths.

#### Is there anything you'd like reviewers to focus on?

The main changes are in @eslint/eslintrc ([PR](https://github.com/eslint/eslintrc/pull/71)).
It should be merged and released first before changes here can be applied.

2022-02-17 01:09 UTC, nzakas requested changes
Can you add some tests for this?

2022-02-17 09:59 UTC, daidodo commented
> Can you add some tests for this?

Could you tell me what tests you are expecting? I thought there were no API changes so existing tests should be enough.
Please also note that the tests failed because https://github.com/eslint/eslintrc/pull/71 hasn't been released.
Thanks!

2022-02-23 17:44 UTC, mdjermanovic commented
We recently added some tests that would fail if this doesn't work at all: https://github.com/eslint/eslint/commit/bfaa5488bbc794c0d160fb55bd277a2c618953b2

Maybe we could add another test in `tests/lib/cli-engine/cli-engine.js` to check entire configurations, and also make sure that we won't accidentally revert to passing string paths:

```js
it("should pass functions that load built-in configs to CascadingConfigArrayFactory", () => {

    let constructorArgs;

    const eslintrc = require("@eslint/eslintrc");
    const { CLIEngine } = proxyquire("../../../lib/cli-engine/cli-engine", {
        "@eslint/eslintrc": {
            ...eslintrc,
            Legacy: {
                ...eslintrc.Legacy,
                CascadingConfigArrayFactory: class extends CascadingConfigArrayFactory {
                    constructor(...args) {
                        constructorArgs = args;
                        super(...args);
                    }
                }
            }
        }
    });

    // eslint-disable-next-line no-new -- Testing side effects
    new CLIEngine();

    const [options] = constructorArgs;

    assert.strictEqual(typeof options.eslintRecommendedPath, "undefined");
    assert.strictEqual(typeof options.getEslintRecommendedConfig, "function");
    assert.deepStrictEqual(options.getEslintRecommendedConfig(), require("../../../conf/eslint-recommended"));
    assert.strictEqual(typeof options.eslintAllPath, "undefined");
    assert.strictEqual(typeof options.getEslintAllConfig, "function");
    assert.deepStrictEqual(options.getEslintAllConfig(), require("../../../conf/eslint-all"));

});
```

@nzakas did you mean something like this?

2022-02-24 01:20 UTC, nzakas commented
I’d much prefer a simpler test where we check configs with eslint:recommended and eslint:all produce the desired results.

2022-02-25 01:16 UTC, nzakas approved these changes

2022-02-25 01:17 UTC, nzakas commented
Ah good call. In that case I think we are good. 👍

I’m assuming the lint error will resolve when eslintrc is upgraded.

2022-02-25 22:27 UTC, mdjermanovic commented
I'll close-reopen to run checks with these changes on top of the latest `main`.

2022-02-25 22:37 UTC, mdjermanovic approved these changes
LGTM, thanks for contributing!

2022-02-25 22:38 UTC, merged