docs: remove install command
eslint/eslint pull request #16084
Opened 2022-07-02 13:05 UTC by harish-sethuraman

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Remove install command 

related: 
- https://github.com/eslint/eslint/issues/16050

#### Is there anything you'd like reviewers to focus on?

2022-07-04 02:32 UTC, aladdin-add requested changes
can you also update it in the readme?

2022-07-04 10:57 UTC, snitin315 reviewed
Can you fix conflicts? Otherwise, LGTM

2022-07-04 10:59 UTC, snitin315 commented
Also you can use keywords like `Fix`, `Resolve`, `Closes`,  etc when linking the issue it will close the issue automatically when PR is merged.

2022-07-05 02:14 UTC, aladdin-add approved these changes
LGTM, thanks!

2022-07-05 03:08 UTC, snitin315 approved these changes
LGTM, not sure about merging since the release-monitor check is pending.

2022-07-07 00:53 UTC, nzakas requested changes

2022-07-07 00:53 UTC, nzakas commented on README.md
> +# or
I think we can leave off Yarn now

2022-07-07 00:53 UTC, nzakas commented on README.md
> +The easiest way to initialize ESLint is:
```suggestion
You can install and configure ESLint using this command:
```

2022-07-07 00:53 UTC, nzakas commented on docs/src/user-guide/getting-started.md
> +The easiest way to initialize ESLint is:
```suggestion
You can install and configure ESLint using this command:
```

2022-07-09 17:52 UTC, harish-sethuraman commented on README.md
> +# or
Done

2022-07-09 17:52 UTC, harish-sethuraman commented on README.md
> +The easiest way to initialize ESLint is:
Done

2022-07-09 17:52 UTC, harish-sethuraman commented on docs/src/user-guide/getting-started.md
> +The easiest way to initialize ESLint is:
Done

2022-07-12 00:51 UTC, nzakas approved these changes
LGTM. In general we don’t merge things when the release monitor is in the pending state unless it is specifically for a patch release.

2022-07-12 00:51 UTC, merged