fix: check for Object.create() without explicit return value in
eslint/eslint pull request #16420
Opened 2022-10-13 13:04 UTC by hirasawayuki

getter-return

Fixes: #16419

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

#### Is there anything you'd like reviewers to focus on?

2022-10-13 20:23 UTC, mdjermanovic commented
Note: we should merge this change as `feat` because it generates more warnings.

2022-10-13 21:04 UTC, mdjermanovic requested changes

2022-10-14 17:35 UTC, hirasawayuki commented on lib/rules/getter-return.js
> +                        const calleePropName = astUtils.getStaticPropertyName(parent.parent.parent.parent.parent.callee);
Thank you for review! I fixed to check the Object name and several test cases have been added 😃

2022-10-21 08:56 UTC, mdjermanovic approved these changes
LGTM, thanks for contributing!

2022-10-21 09:07 UTC, merged

2022-11-03 20:46 UTC, nzakas commented
@hirasawayuki we'd like to pay you for this contribution. Please email us at contact (at) eslint (dot) org. Thanks!