Add heading to justification explanation
eslint/eslint pull request #16430
Opened 2022-10-16 07:58 UTC by maritaria

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Places the documentation related to justifications (on comment directives) in its own section so it may be more easily found from the table of contents.

#### Is there anything you'd like reviewers to focus on?

Spelling and terminology used in new text

2022-10-16 11:24 UTC, maritaria commented
Rebased to fix commit message

2022-10-16 15:12 UTC, mdjermanovic approved these changes
LGTM, thanks!

I'll merge this when we fix CI.

2022-10-17 18:09 UTC, nzakas requested changes

2022-10-31 18:54 UTC, nzakas approved these changes

2022-10-31 18:54 UTC, merged