fix: use `baseConfig` constructor option in FlatESLint
eslint/eslint pull request #16432
Opened 2022-10-16 20:53 UTC by mdjermanovic

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Fixes https://github.com/eslint/eslint/issues/16341

#### What changes did you make? (Give an overview)

Fixed `FlatESLint` class to use `baseConfig`.

#### Is there anything you'd like reviewers to focus on?

2022-10-17 20:27 UTC, nzakas requested changes
Overall LGTM. One scenario missing in the tests is when you are using both baseConfig and overrideConfig. It would be helpful to ensure that those are inserted in the correct order.

2022-10-20 20:27 UTC, mdjermanovic commented
> One scenario missing in the tests is when you are using both baseConfig and overrideConfig. It would be helpful to ensure that those are inserted in the correct order.

Done. I've added a test with baseConfig + overrideConfig, and a test with baseConfig + config file + overrideConfig.

2022-10-20 20:40 UTC, mdjermanovic commented on lib/eslint/flat-eslint.js
> +            configs.push(...fileConfig);
By basePath that was passed in, do you mean `overrideConfigFile: <string>` where the override config file is in another directory? We decided that in that case basePath should be `cwd` (https://github.com/eslint/eslint/issues/15683).

basePath is calculated and set here:

https://github.com/eslint/eslint/blob/c259ab74cf504671b88c49036d3628ab966a1cdc/lib/eslint/flat-eslint.js#L300-L315

There are three cases:

* Normal `eslint.config.js` lookup (`overrideConfigFile: false`, default): basePath = the directory where `eslint.config.js` was found.
* Use an alternative config file (`overrideConfigFile: <string>`): basePath = cwd
* Don't use any config files (`overrideConfigFile: true`): basePath = cwd

2022-10-21 20:21 UTC, nzakas commented on lib/eslint/flat-eslint.js
> +            configs.push(...fileConfig);
Got it. :+1: just wanted to double check.

2022-10-21 20:21 UTC, nzakas approved these changes

2022-10-21 20:31 UTC, merged