feat: `no-obj-calls` support `Intl`
eslint/eslint pull request #16543
Opened 2022-11-12 08:37 UTC by sosukesuzuki

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Fixes #16393

`no-obj-call` supports `Intl` objects.

#### Is there anything you'd like reviewers to focus on?

Implementation is simple, so please focus tests and docs.

2022-11-12 19:07 UTC, mdjermanovic requested changes

2022-11-12 19:07 UTC, mdjermanovic commented on docs/src/rules/no-obj-calls.md
> +And the [ECMAScript Internationalization API Specification](https://tc39.es/ecma402/#intl-object) make it clear that `Intl` cannot be involed:
```suggestion
And the [ECMAScript Internationalization API Specification](https://tc39.es/ecma402/#intl-object) makes it clear that `Intl` cannot be invoked:
```

2022-11-13 01:05 UTC, snitin315 approved these changes
The code LGTM. One suggestion on the docs above.

2022-11-13 16:18 UTC, mdjermanovic approved these changes
LGTM, thanks!

2022-11-13 16:19 UTC, merged