feat: `require-unicode-regexp` add suggestions
eslint/eslint pull request #17007
Opened 2023-03-21 21:15 UTC by JoshuaKGoldberg

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[x] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Adds a `suggest` array to the fixes for the `require-unicode-regexp` rule.

#### Is there anything you'd like reviewers to focus on?

🤷

2023-03-22 13:42 UTC, mdjermanovic requested changes
Thanks for working on this!

2023-03-22 13:42 UTC, mdjermanovic commented on lib/rules/require-unicode-regexp.js
> +                        ]
We should check if the regex literal would be syntactically valid with the `u` flag, and not provide the suggestion if it wouldn't be valid.

For example:

```js
/\a/
```

If the rule provides a suggestion that adds `u`, after the suggestion is applied the code will have a parsing error:

```js
/\a/u // Parsing error: Invalid regular expression: /\a/: Invalid escape
```

You can check how this is implemented in the [`no-misleading-character-class`](https://github.com/eslint/eslint/blob/1fbf1184fed57df02640aad4659afb54dc26a2e9/lib/rules/no-misleading-character-class.js#L195) rule.

(the same for the RegExp constructor branch)

2023-03-22 17:30 UTC, JoshuaKGoldberg commented on lib/rules/utils/unicode/regular-expressions.js
> +module.exports.REGEXPP_LATEST_ECMA_VERSION = REGEXPP_LATEST_ECMA_VERSION;
Is there a precedent for exporting constants like this? I couldn't find one.

2023-03-22 18:26 UTC, JoshuaKGoldberg commented on lib/rules/require-unicode-regexp.js
@fasttime https://github.com/eslint/eslint/pull/17007#issuecomment-1480017098 to a file so I can thread it:

> Thanks @JoshuaKGoldberg! For `new RegExp('foo', false)` I am getting an inconsistent suggestion. The suggested change is `new RegExp('foo', falsue)`. Can we adjust this somehow, or remove the suggestion?

2023-03-22 18:27 UTC, JoshuaKGoldberg commented on lib/rules/require-unicode-regexp.js
> `new RegExp('foo', false)`

Ah, nice edge case to test for - thanks for pointing it out! I'll add logic that the flags node should be a string literal.

Note that that's not the proper way to call `new RegExp`, I think? Per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp#parameters the second parameter, `flags`, should be a string.

2023-03-23 07:08 UTC, fasttime commented
For `RegExp('', a = 'g')`, the suggested change is `RegExp('', a = 'g' + "u")`, which makes sense, but maybe `RegExp('', (a = 'g') + "u")` would be a better choice because of reduced side effects.

Anyway, I don't see any unit tests where the second argument of `RegExp` is an assignment. Shall we add some?

2023-03-23 09:16 UTC, mdjermanovic commented on lib/rules/utils/unicode/regular-expressions.js
We use `regexpp` for purposes other than Unicode too, so I think this should be maintained in the existing `rules/utils/ast-utils.js` or in a new `rules/utils/regular-expressions.js` rather than under `rules/utils/unicode/`

2023-03-23 09:27 UTC, mdjermanovic commented
> For `RegExp('', a = 'g')`, the suggested change is `RegExp('', a = 'g' + "u")`, which makes sense, but maybe `RegExp('', (a = 'g') + "u")` would be a better choice because of reduced side effects.

I think it might be best to just not provide suggestions that add `+ "u"`. For example, if the code is `const flags = "g"; const regex = new RegExp("foo", flags);`, user would probably want `const flags = "gu";` rather than `new RegExp("foo", flags + "u");`.

2023-03-23 10:12 UTC, mdjermanovic commented on lib/rules/require-unicode-regexp.js
> +                                                if (flagsNode.type === "Literal" && typeof flagsNode.value === "string") {
```suggestion
                                                if ((flagsNode.type === "Literal" && typeof flagsNode.value === "string") || flagsNode.type === "TemplateLiteral") {
```

We can include template literals here.

2023-03-23 15:41 UTC, mdjermanovic commented on lib/rules/utils/regular-expressions.js
> +module.exports.REGEXPP_LATEST_ECMA_VERSION = 2022;
Can we avoid duplicating the constant value? We could write the module like this:

```js
"use strict";

const REGEXPP_LATEST_ECMA_VERSION = 2022;

function isValidWithUnicodeFlag(ecmaVersion, pattern) {
    // ...
}

module.exports = {
    REGEXPP_LATEST_ECMA_VERSION,
    isValidWithUnicodeFlag
};
```

2023-03-23 15:48 UTC, mdjermanovic commented on lib/rules/utils/regular-expressions.js
> +module.exports.REGEXPP_LATEST_ECMA_VERSION = 2022;
Also, can you please add `@fileoverview` and `@author` tags to the new file? Here's an example:

https://github.com/eslint/eslint/blob/1fbf1184fed57df02640aad4659afb54dc26a2e9/lib/rules/utils/ast-utils.js#L1-L4

2023-03-23 17:40 UTC, JoshuaKGoldberg commented
Test failure is unrelated:

```plaintext
  1) CLIEngine
       "before all" hook in "CLIEngine":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\eslint\eslint\tests\lib\cli-engine\cli-engine.js)
      at process.processImmediate (node:internal/timers:476:21)
```

2023-03-24 09:45 UTC, fasttime reviewed
Noticed that we have an existing false positive with `RegExp(...patternAndFlags)`. If we don't fix this here, we should do it in a new PR.

2023-03-27 19:44 UTC, nzakas commented on lib/rules/utils/regular-expressions.js
> + * @author Toru Nagashima
The intent is to identify who created the file. In cases like this, we generally include the person who created the file (@JoshuaKGoldberg) and also the person who wrote most of the code (Toru), as it is a nice way to identify the file's origins.

2023-03-28 05:26 UTC, fasttime approved these changes
LGTM!

2023-03-28 18:15 UTC, nzakas approved these changes
LGTM. Would like @mdjermanovic to verify his concerns were addressed.

2023-03-28 19:20 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-03-28 19:21 UTC, merged