docs: Revert all changes after the license change
eslint/eslint pull request #17227
Opened 2023-05-27 18:15 UTC by mdjermanovic

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

Refs https://github.com/eslint/eslint/issues/17225, fixes step 2.

#### What changes did you make? (Give an overview)

Checked out https://github.com/eslint/eslint/commit/b3634f695ddab6a82c0a9b1d8695e62b60d23366 and copied its `docs/` folder over the current one.

#### Is there anything you'd like reviewers to focus on?

This reverts all changes after https://github.com/eslint/eslint/commit/b3634f695ddab6a82c0a9b1d8695e62b60d23366, including the bot's and team members' commits. Is that okay?

2023-05-27 19:04 UTC, amareshsm commented
> Also, this reverts only docs parts of the commits. For example, https://github.com/eslint/eslint/commit/880a4317b949e575a4a6c5e8baaba1eea7674cc6 had changes in both code and docs. Its code changes will stay, while the docs changes will be removed. Is that okay?

After reverting this PR are we immediately going to resubmit the removed documentation?

2023-05-29 18:44 UTC, nzakas requested changes
Thanks for going through and doing this.

I started leaving notes on each file, but basically we just need to revert the *.md files, as those are the only ones that contain documentation. All of the other file types are covered under the MIT license only and we should leave as-is.

2023-05-29 18:44 UTC, nzakas commented on docs/package.json
> +    "version": "8.36.0",
I think we probably want to keep this at 8.41.0 to match the ESLint version?

2023-05-29 18:44 UTC, nzakas commented on docs/src/_data/sites/en.yml
> -    latest: Latest
I think we need to keep this?

2023-05-29 18:44 UTC, nzakas commented on docs/src/_data/sites/zh-hans.yml
> -    latest: 最新
Ditto

2023-05-29 18:44 UTC, nzakas commented on docs/src/_includes/components/language-switcher.html
Safe to keep

2023-05-29 18:44 UTC, nzakas commented on docs/src/_includes/layouts/base.html
Safe to keep

2023-05-29 18:44 UTC, nzakas commented on docs/src/_includes/layouts/doc.html
Safe to keep

2023-05-29 18:44 UTC, nzakas commented on docs/src/assets/js/scroll-up-btn.js
Safe to Keep

2023-05-29 18:44 UTC, nzakas commented on docs/src/assets/scss/components/alert.scss
Safe to keep

2023-05-30 12:03 UTC, aladdin-add approved these changes
LGTM, thanks! 👍

2023-05-30 18:54 UTC, nzakas approved these changes
LGTM. Just leaving open so we can coordinate how we want to merge this in.

2023-06-05 20:48 UTC, merged