feat: `no-control-regex` support v flag
eslint/eslint pull request #17405
Opened 2023-07-23 02:46 UTC by ota-meshi

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))

#### What changes did you make? (Give an overview)

Refs #17223

This PR modifies the `no-control-regex` rule and adds support for regexp `v` flag.

#### Is there anything you'd like reviewers to focus on?

2023-07-24 15:21 UTC, nzakas requested changes
Code LGTM. Can we add in some more tests that use regex literals, too?

2023-07-25 00:53 UTC, ota-meshi commented
Thank you for reviewing this PR. I added two testcases. Could you please check again?

2023-07-25 18:58 UTC, nzakas approved these changes
LGTM, thanks! Would like @mdjermanovic to verify before merging.

2023-07-25 22:42 UTC, mdjermanovic reviewed
Some weird behavior with `"uv"`:

```js
/* eslint no-control-regex: ["error"] */

/\x11/; // error: Unexpected control character(s) in regular expression: \x11.

RegExp("", "uv"); // error: Unexpected control character(s) in regular expression: \x11.

```

I'm guessing this happens because in this case `validatePattern` throws before `onPatternEnter` is called, so moving `this._controlChars = [];` into `collectControlChars` might help (though I'm not sure why it wasn't already there, i.e. is there a reason why `onPatternEnter` was used for this?).

2023-07-25 23:56 UTC, ota-meshi commented
Thank you for finding the bug!

I added `this._controlChars = []` to `collectControlChars`.
However, I left the `onPatternEnter`. I added a comment as to why. Could you please check that?

```js
        /*
         * `RegExpValidator` may parse the pattern twice in one `validatePattern`.
         * So `this._controlChars` should be cleared here as well.
         *
         * For example, the `/(?<a>\x1f)/` regex will parse the pattern twice.
         * This is based on the content described in Annex B.
         * If the regex contains a `GroupName` and the `u` flag is not used, `ParseText` will be called twice.
         * See https://tc39.es/ecma262/2023/multipage/additional-ecmascript-features-for-web-browsers.html#sec-parsepattern-annexb
         */
```

2023-07-26 11:30 UTC, mdjermanovic commented
Thanks for the explanation, very useful! I hadn't thought of that.

2023-07-26 11:51 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-07-26 11:52 UTC, merged