docs: update with "Specifying Parser Options"
eslint/eslint pull request #17435
Opened 2023-07-31 03:18 UTC by Ryan-Dia

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
I added Supplementary explanations to the docs 

#### Is there anything you'd like reviewers to focus on?

Motivation

After reading the explanation, I thought that having a summary at the end would be helpful for better comprehension. Therefore, I added a summarizing section at the end of the text. This may assist readers who might have had difficulty understanding the earlier parts or those who need a more organized overview. Additionally, it will make the content easier to read and more reader-friendly.

I'm always grateful

2023-07-31 16:04 UTC, nzakas requested changes
Thanks. The additional sentence looks good, but you've also submitted a bunch of formatting changes. Can you please revert those?

2023-07-31 18:11 UTC, fasttime commented on docs/src/use/configure/language-options.md
> +By the same token, supporting ES6 syntax is not the same as supporting new ES6 globals (e.g., new types such as `Set`). For ES6 syntax, use `{ "parserOptions": { "ecmaVersion": 6 } }`; for new ES6 gl
```suggestion
By the same token, supporting ES6 syntax is not the same as supporting new ES6 globals (e.g., new types such as `Set`). For ES6 syntax, use `{ "parserOptions": { "ecmaVersion": 6 } }`; for new ES6 global variables, use `{ "env": { "es6": true } }`. Setting `{ "env": { "es6": true } }` enables ES6 syntax automatically, but `{ "parserOptions": { "ecmaVersion": 6 } }` does not enable ES6 globals automatically. In summary, to support only ES6 syntax, use `{ "parserOptions": { "ecmaVersion": 6 } }`, and to support both ES6 syntax and new ES6 global variables, such as `Set` and others, use `{ "env": { "es6": true } }`.
```

Just a suggestion to improve formatting.

2023-08-01 01:20 UTC, Ryan-Dia commented
> Thanks. The additional sentence looks good, but you've also submitted a bunch of formatting changes. Can you please revert those?

I apologize. I have reverted the formatting changes to their original state.

2023-08-01 15:38 UTC, nzakas approved these changes
LGTM, thanks. Would like @fasttime to verify his comments were addressed before merging.

2023-08-01 21:56 UTC, mdjermanovic approved these changes

2023-08-02 04:03 UTC, fasttime approved these changes
LGTM, thanks!

2023-08-02 04:04 UTC, merged