feat!: assert suggestion messages are unique in rule testers
eslint/eslint pull request #17532
Opened 2023-09-05 05:40 UTC by JoshuaKGoldberg

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[x] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Added logic to the two rule tester classes to assert that no suggestion contains the same hydrated description as a previous suggestion in the same error. 

#### Is there anything you'd like reviewers to focus on?

Was the consensus for asserting on the rule's _actual_ reported suggestions or _expected_? I went with _actual_ to start because that feels more comprehensive.

2023-09-05 21:13 UTC, JoshuaKGoldberg commented
#16908 is ready for review. Marked as draft for now as it's a breaking change.

2023-09-07 16:21 UTC, nzakas approved these changes
LGTM. And yes, the consensus was to track the actual messages produced from a rule.

We'll need to hold off on this until we start merging PRs for v9.

2023-11-05 12:06 UTC, mdjermanovic requested changes

2023-11-05 12:06 UTC, mdjermanovic commented on tests/lib/rule-tester/rule-tester.js
> +            }, "Rules with suggestions must set the `meta.hasSuggestions` property to `true`");
This change doesn't seem necessary?

2023-11-06 11:53 UTC, mdjermanovic commented
Just https://github.com/eslint/eslint/pull/17532#discussion_r1382559056, then LGTM.

2023-11-06 12:16 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-12-20 16:23 UTC, merged