fix: wrong suggest and message in `no-misleading-character-class`
eslint/eslint pull request #17571
Opened 2023-09-16 12:18 UTC by ota-meshi

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

close #17537

Fixed incorrect message and changed to not suggest u flag, when Unicode code point escapes were included.

#### Is there anything you'd like reviewers to focus on?

2023-09-16 12:58 UTC, ota-meshi commented
Hmm. I don't really understand why Browser Test fails.
I suspect that the webdriverio update may be the cause, but I'm not sure.

https://github.com/webdriverio/webdriverio/pull/11175

2023-09-16 20:38 UTC, mdjermanovic commented
> Hmm. I don't really understand why Browser Test fails. I suspect that the webdriverio update may be the cause, but I'm not sure.
> 
> [webdriverio/webdriverio#11175](https://github.com/webdriverio/webdriverio/pull/11175)

It's failing on `main` too. I opened https://github.com/eslint/eslint/issues/17572. Shouldn't be a blocker for this PR.

2023-09-17 11:52 UTC, mdjermanovic requested changes
Just a small suggestion about the tests, then LGTM.

2023-09-17 11:52 UTC, mdjermanovic commented on tests/lib/rules/no-misleading-character-class.js
> +            env: { es2020: true },
```suggestion
```

This isn't necessary for this test case, so it might be confusing why it is here.

2023-09-17 11:52 UTC, mdjermanovic commented on tests/lib/rules/no-misleading-character-class.js
> +            env: { es2020: true },
```suggestion
```

2023-09-17 11:52 UTC, mdjermanovic commented on tests/lib/rules/no-misleading-character-class.js
> +            env: { es2020: true },
```suggestion
```

2023-09-17 11:52 UTC, mdjermanovic commented on tests/lib/rules/no-misleading-character-class.js
> +            env: { es2020: true },
```suggestion
```

2023-09-17 16:39 UTC, ota-meshi commented
Thank you for checking this PR! I changed this PR.

2023-09-18 06:46 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-09-18 06:47 UTC, merged