feat: add suggestions to array-callback-return
eslint/eslint pull request #17590
Opened 2023-09-19 12:44 UTC by Tanujkanti4441

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
Added suggestions to the `array-callback-return` rule.
The fixer functions of PR #17282 are used to implement suggestions.

#### Is there anything you'd like reviewers to focus on?

Fixes- #17282

2023-09-19 15:25 UTC, mdjermanovic requested changes

2023-09-19 15:25 UTC, mdjermanovic commented on lib/rules/array-callback-return.js
> +        type: "suggestion",
```suggestion
        type: "problem",
```

This change should be reverted, as the `meta.type` field isn't related to providing editor suggestions. `type: "problem"` means that the rule reports possible errors in code, which is the case with this rule. `type: "suggestion"` means that the rule only enforces preferences. Both kinds of rules can have editor suggestions :)

2023-09-19 15:31 UTC, mdjermanovic commented
Linting fails with this error:

```
Error:   224:25  error  `meta.hasSuggestions` cannot be `true` for non-suggestable rules  eslint-plugin/require-meta-has-suggestions
```

Looks like `eslint-plugin/require-meta-has-suggestions` can't detect that this rule does provide suggestions. I think the right solution, at the moment, is to disable `eslint-plugin/require-meta-has-suggestions`:

```diff
+ // eslint-disable-next-line eslint-plugin/require-meta-has-suggestions -- false positive
hasSuggestions: true,
```

2023-09-19 16:04 UTC, Tanujkanti4441 commented
> Linting fails with this error:
> 
> ```
> Error:   224:25  error  `meta.hasSuggestions` cannot be `true` for non-suggestable rules  eslint-plugin/require-meta-has-suggestions
> ```
> 
> Looks like `eslint-plugin/require-meta-has-suggestions` can't detect that this rule does provide suggestions. I think the right solution, at the moment, is to disable `eslint-plugin/require-meta-has-suggestions`:
> 
> ```diff
> + // eslint-disable-next-line eslint-plugin/require-meta-has-suggestions -- false positive
> hasSuggestions: true,
> ```

Wow this saves me. I am still wondering what causing this error even though all tests are clear.

2023-09-22 13:42 UTC, mdjermanovic requested changes

2023-09-22 13:42 UTC, mdjermanovic commented on lib/rules/array-callback-return.js
> +            // let messageId = null;
```suggestion
```

We can remove this if it's not needed.

2023-09-22 13:42 UTC, mdjermanovic commented on lib/rules/array-callback-return.js
> +                        suggest: messageAndSuggestions.suggest !== 0 ? messageAndSuggestions.suggest : null
```suggestion
                        suggest: messageAndSuggestions.suggest.length !== 0 ? messageAndSuggestions.suggest : null
```

2023-09-22 13:42 UTC, mdjermanovic commented on tests/lib/rules/array-callback-return.js
> +                    { output: "foo.forEach(x => {x})" }
Can you add `messageId` to all suggestion test objects? Also, can you add `suggestions` to all test cases where the rule provides suggestions? This is for better testing and will soon be mandatory per [RFC #84](https://github.com/eslint/rfcs/blob/main/designs/2021-stricter-rule-test-validation/README.md).

2023-09-22 20:04 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-09-22 20:05 UTC, merged