Update multiline-ternary.md
eslint/eslint pull request #17610
Opened 2023-09-28 07:16 UTC by AshiotisCy

I have thought of a new way to implement the multiline-ternary.

I have moved the ? and : below the logical expression to make it more readable and understandable in cases were logical expressions get more complex.

Also this way has a look of a tree to know where the first "IF" statement starts and where it finishes.

#### Prerequisites checklist

- [ ] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

#### Is there anything you'd like reviewers to focus on?

2023-09-28 08:27 UTC, mdjermanovic commented
Hi @AshiotisCy, thanks for the PR!

> I have thought of a new way to implement the multiline-ternary.

Can you please clarify the intent of this PR, is it to change the way the rule works or just add more examples of how the rule already works?

2023-09-28 10:19 UTC, AshiotisCy commented
> Hi @AshiotisCy, thanks for the PR!
> 
> > I have thought of a new way to implement the multiline-ternary.
> 
> Can you please clarify the intent of this PR, is it to change the way the rule works or just add more examples of how the rule already works?

Its basically to change the view the multiline-tenary works for 

> Hi @AshiotisCy, thanks for the PR!
> 
> > I have thought of a new way to implement the multiline-ternary.
> 
> Can you please clarify the intent of this PR, is it to change the way the rule works or just add more examples of how the rule already works?

Is to change the way the rule works. I find the way i provided easier to read and understand since it will provide a more clear way when you have multiple line with ternary.

The example i provided is to give a more clear vision 
`foo > bar
    ? (baz > qux
        ? value1
        : value2)
    : value3;`
 
 rather than:
 
 `foo > bar ?
    (baz > qux ?
        value1 :
        value2) :
    value3;`
    
   With the 1 option you can see where the first '?' starts along with its closing ':'

2023-10-02 10:01 UTC, mdjermanovic commented
Stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates), so we're not making any changes to the way the `multiline-ternary` rule works.

If you'd like, we can accept adding more correct/incorrect examples of how the rule already works, but I think we should keep the existing examples as well.

2023-10-02 10:06 UTC, mdjermanovic commented
> ```
> foo > bar
>     ? (baz > qux
>         ? value1
>         : value2)
>     : value3;
> ```
> 
> 
>     
>   
> 
> rather than:
> 
> 
> ```
>  foo > bar ?
>     (baz > qux ?
>         value1 :
>         value2) :
>     value3;
> ```

Note that this is controlled by the [operator-linebreak](https://eslint.org/docs/latest/rules/operator-linebreak) rule. As for the `multiline-ternary` rule, both examples are valid.

2023-10-02 10:14 UTC, mdjermanovic requested changes

2023-10-02 12:42 UTC, AshiotisCy commented
> Stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates), so we're not making any changes to the way the `multiline-ternary` rule works.
> 
> If you'd like, we can accept adding more correct/incorrect examples of how the rule already works, but I think we should keep the existing examples as well.

Ok then lets just add it as another correct example

2023-10-02 13:13 UTC, AshiotisCy commented on docs/src/rules/multiline-ternary.md
> -    value3;
Done

2023-10-02 13:13 UTC, AshiotisCy commented on docs/src/rules/multiline-ternary.md
> -    value : value2;
Done

2023-10-02 13:13 UTC, AshiotisCy commented on docs/src/rules/multiline-ternary.md
> -) : value3;
Done

2023-10-02 13:13 UTC, AshiotisCy commented on docs/src/rules/multiline-ternary.md
> +    : value3;
You are right, I have removed it from the the "never" example

2023-10-02 14:15 UTC, mdjermanovic approved these changes
LGTM, thanks!

2023-10-02 14:16 UTC, merged