feat: Added `ignoreFilenamesPatterns` option to the `no-restricted-imports` rule to be able to allow restricted imports in specific places
eslint/eslint pull request #18089
Opened 2024-02-07 16:12 UTC by vovkvlad

#### What changes did you make? (Give an overview)
We are using `no-restricted-imports` rule pretty extensively to limit devs doing wrong stuff, and also to help ourselves during migrations. But the thing is, in almost all our use cases we need a way to whitelist some directory for some specific option, like, for example, we want to prohibit devs from using particular imports from library in favor of our local wrapper of it which does additional logic. In this case local wrapper should allow the restricted import for this particular library, but still disallow all other restricted imports in the project..

Before we were achieving this by leveraging `eslint` `overrides`. So the config looked like this:

```js
// eslintrc.js:
module.exports = {
  // ... other props
  rules: [
    no-restricted-imports': [
      2,
      {
        patterns: [
          '@companyname/privateLib/*',
          '@testing-library/*'
        ],
      },
    ],
  ],
  overrides: [
    {
      files: [
        'src/build-tools/**/*.js',
        'src/index.js',
      ],
      rules: {
        'no-restricted-imports': [
          0,
          { patterns: ['@companyname/privateLib/*'] },
        ],
      },
    },
    {
      files: [
        'src/**/*.test.js',
        'src/**/*.test.helpers.js',
        'src/**/test.helpers.js',
        'src/**/*',
      ],
      rules: {
        'no-restricted-imports': [0, { patterns: ['@testing-library/*'] }],
      },
    },
  ]
}
```

But with recent updates to the latest version of eslint overrides are not working in that way - they are disabling the whole rule for the given `files` in `overrides` instead of switching off specific option.

That's why I got the idea of introducing `ignoreFilenamesPatterns` option to whitelist directories where specific restricted import is allowed.

Let me know if I'm missing anything, looking forward to any feedback on this proposal

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[X] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**What rule do you want to change?**
`no-restricted-impotrs`

**What change do you want to make (place an "X" next to just one item)?**

[ ] Generate more warnings
[x] Generate fewer warnings
[ ] Implement autofix
[ ] Implement suggestions

**How will the change be implemented (place an "X" next to just one item)?**

[x] A new option
[ ] A new default behavior
[ ] Other

**Please provide some example code that this change will affect:**

```js
// filePath: /user.name/projects/appName/src/build-scripts/compile.js

/*eslintrc.js:
no-restricted-imports: ["error", { patterns: [{
    group: ["@companyName/privateLib/*"],
    message: "Please do not use privateLib in the codebase it is for build utils only.",
    ignoreFilenamesPatterns: ["**/src/build-scripts/**"]
}]}]*/

import { util } from @companyName/privateLib/compile-utils.js
```

**What does the rule currently do for this code?**
The rule will generate an error because the import is restricted

**What will the rule do after it's changed?**
The rule won't produce an error because the fileName ` /user.name/projects/appName/src/build-scripts/compile.js` is being whitelisted by `ignoreFilenamesPatterns` parameters.

#### Is there anything you'd like reviewers to focus on?

2024-02-07 17:13 UTC, Tanujkanti4441 requested changes

2024-02-07 17:13 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +This option in `path` is an array of filename patterns where current restricted import should be allowed.
```suggestion
This option in `paths` is an array of filename patterns where current restricted import should be allowed.
```

2024-02-07 17:13 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +If the filePath of the linted file is matched by one of the ignoreFilenamesPatterns then error will not be produced
```suggestion
If the filePath of the linted file is matched by one of the `ignoreFilenamesPatterns` then error will not be produced.
```

2024-02-07 17:13 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +Examples of **incorrect** code for `ignoreFilenamesPatterns` option:
```suggestion
Examples of **incorrect** code for `ignoreFilenamesPatterns` option in `patterns`:
```

2024-02-07 17:20 UTC, Tanujkanti4441 commented
How about if we name this option something like `allowFilenames` if it is allowing the modules to be imported only in the specified files. (just an opinion)

2024-02-07 17:38 UTC, mdjermanovic commented
I'm not in favor of adding filename-related options to core rules, because the same functionality can always be achieved with `overrides` in the config file.

> Before we were achieving this by leveraging `eslint` `overrides`. So the config looked like this:
> 
> ```js
> // eslintrc.js:
> module.exports = {
>   // ... other props
>   rules: [
>     no-restricted-imports': [
>       2,
>       {
>         patterns: [
>           '@companyname/privateLib/*',
>           '@testing-library/*'
>         ],
>       },
>     ],
>   ],
>   overrides: [
>     {
>       files: [
>         'src/build-tools/**/*.js',
>         'src/index.js',
>       ],
>       rules: {
>         'no-restricted-imports': [
>           0,
>           { patterns: ['@companyname/privateLib/*'] },
>         ],
>       },
>     },
>     {
>       files: [
>         'src/**/*.test.js',
>         'src/**/*.test.helpers.js',
>         'src/**/test.helpers.js',
>         'src/**/*',
>       ],
>       rules: {
>         'no-restricted-imports': [0, { patterns: ['@testing-library/*'] }],
>       },
>     },
>   ]
> }
> ```
> 
> But with recent updates to the latest version of eslint overrides are not working in that way - they are disabling the whole rule for the given `files` in `overrides` instead of switching off specific option

This configuration should disable the whole rule for the given `files` in `overrides` in all versions of ESLint. Can you check in which versions is this behavior different?

2024-02-07 17:54 UTC, mdjermanovic commented
Instead of switching off specific options for specific files (which was never intended to work), you could reconfigure the rule for those files:

```js
// eslintrc.js:
module.exports = {
  // ... other props
  rules: [
    no-restricted-imports': [
      2,
      {
        patterns: [
          '@companyname/privateLib/*',
          '@testing-library/*'
        ],
      },
    ],
  ],
  overrides: [
    {
      files: [
        'src/build-tools/**/*.js',
        'src/index.js',
      ],
      rules: {
        'no-restricted-imports': [
          2,
          { patterns: ['@testing-library/*'] },
        ],
      },
    },
    {
      files: [
        'src/**/*.test.js',
        'src/**/*.test.helpers.js',
        'src/**/test.helpers.js',
        'src/**/*',
      ],
      rules: {
        'no-restricted-imports': [2, { patterns: ['@companyname/privateLib/*'] }],
      },
    },
  ]
}
```

2024-02-07 17:55 UTC, nzakas commented
I'm also not in favor of adding this as a new option given that there are already ways to achieve this using a config file.

2024-02-07 17:55 UTC, closed without merging

2024-02-08 10:24 UTC, vovkvlad commented
I see your point. I was thinking that we can invert overrides, but we have plenty of those, and it will mean that whenever you need to add new restricted import you will have to go over all overrides, and add it there to, and vice-versa - adding new override will require specifying all imports that should be prohibited for those specific files except the ones that should be allowed, which looks a bit tedious considering our extensive use of the rule.

But anyway, thanks for the feedback.