docs: `paths` and `patterns` difference in `no-restricted-imports`
eslint/eslint pull request #18273
Opened 2024-04-05 09:33 UTC by Tanujkanti4441

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)
added difference between the `paths` and `patterns` option of `no-restricted-imports` rule.

#### Is there anything you'd like reviewers to focus on?
Fixes: #18253

2024-04-06 13:13 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +Where `paths` option takes exact import paths, `patterns` option can be used to specify the import paths with more flexibility, allowing for the restriction of multiple modules within the same direct
Done! added examples.

2024-04-10 18:21 UTC, nzakas requested changes

2024-04-10 18:21 UTC, nzakas commented on docs/src/rules/no-restricted-imports.md
> +Where `paths` option takes exact import paths, `patterns` option can be used to specify the import paths with more flexibility, allowing for the restriction of multiple modules within the same direct
```suggestion
Where `paths` option takes exact import paths, `patterns` option can be used to specify the import paths with more flexibility, allowing for the restriction of multiple modules within the same directory. For example:
```

2024-04-10 18:21 UTC, nzakas commented on docs/src/rules/no-restricted-imports.md
> +Here rule will only restrict the `import-foo` module.
```suggestion
This configuration restricts import of the `import-foo` module but wouldn't restrict the import of `import-foo/bar` or `import-foo/baz`. You can use `patterns` to restrict both:
```

2024-04-10 18:21 UTC, nzakas commented on docs/src/rules/no-restricted-imports.md
> +Here rule will restrict all modules inside `import1` directory.
````suggestion
```json
"no-restricted-imports": ["error", {
    "paths": [{
      "name": "import-foo",
    }]
    "patterns": [{
      "group": ["import-foo/ba*"],
    }]
}]
```

This configuration restricts imports not just from `import-foo` using `path`, but also `import-foo/bar` and `import-foo/baz` using `patterns`.
````

2024-04-11 16:32 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +Here rule will restrict all modules inside `import1` directory.
Done!

2024-04-11 16:32 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-imports.md
> +Here rule will only restrict the `import-foo` module.
Done!

2024-04-11 18:15 UTC, nzakas approved these changes
LGTM. Thanks!

2024-04-11 18:15 UTC, merged