fix: allow glob patterns for `restrictedNamedExports` in `no-restrict…
eslint/eslint pull request #18431
Opened 2024-05-08 06:58 UTC by akulsr0

…ed-exports`

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[x] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

Made changes to add support for #18360 

#### Is there anything you'd like reviewers to focus on?

I feel there should be alot more test cases which needs to be added, can add that based on review insights.

2024-05-08 09:06 UTC, Tanujkanti4441 commented
Hi @akulsr0, thanks for the PR, but the accepted proposal was to add a new option name `restrictedNamedExportsPattern` that will be a string containing regex pattern to specify the exports to restrict. Can you do the same?

2024-05-08 09:20 UTC, akulsr0 commented
Hi @Tanujkanti4441, it seems having `restrictedNamedExportsPattern` and `restrictedNamedExports` both would be repetitive. Since, we can do check for regular strings and string patterns with one single option, added that way.

2024-05-08 09:46 UTC, Tanujkanti4441 commented
> Hi @Tanujkanti4441, it seems having `restrictedNamedExportsPattern` and `restrictedNamedExports` both would be repetitive. Since, we can do check for regular strings and string patterns with one single option, added that way.

since something like this is already done in [no-restricted-imports](https://eslint.org/docs/latest/rules/no-restricted-imports) rule so i think it's fine to have both the options.

2024-05-08 10:53 UTC, Tanujkanti4441 requested changes

2024-05-08 10:53 UTC, Tanujkanti4441 commented on lib/rules/no-restricted-exports.js
> +const minimatch = require("minimatch");
can we make the option to accept regex as string.

2024-05-08 10:53 UTC, Tanujkanti4441 commented on lib/rules/no-restricted-exports.js
> +                },
as discussed in the issue this option would be along with `restrictedNamedExports`, here it is in `anyOf` means only one can be used. can you change this.
```js
{
                    type: "object",
                    properties: {
                        restrictedNamedExports: {
                            type: "array",
                            items: {
                                type: "string"
                            },
                            uniqueItems: true
                        },
                       restrictedNamedExportsPattern: {
                            type: "string"
                       }

                    },
                    additionalProperties: false
                },
```

2024-05-08 14:06 UTC, nzakas reviewed
Please be sure to update the documentation as well.

2024-05-08 15:57 UTC, kecrily commented on lib/rules/no-restricted-exports.js
> +        const restrictedNamePatterns = context.options[0] && context.options[0].restrictedNamedExportsPattern || [];
```suggestion
        const restrictedNamePatterns = new Set(context.options[0] && context.options[0].restrictedNamedExportsPattern || []);
```

2024-05-09 11:07 UTC, mdjermanovic requested changes

2024-05-09 11:07 UTC, mdjermanovic commented on lib/rules/no-restricted-exports.js
> +                },
There's no need for another element in `anyOf`, we can add the new property `restrictedNamedExportsPattern` directly into the two existing elements.

Also, I think we agreed in https://github.com/eslint/eslint/issues/18360 that `restrictedNamedExportsPattern` will be a string (one pattern), not an array of strings.

2024-05-10 11:49 UTC, Tanujkanti4441 requested changes

2024-05-10 11:49 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-exports.md
> +```
Can you also add some correct and incorrect example as other options?

2024-05-11 11:56 UTC, Tanujkanti4441 requested changes

2024-05-11 11:56 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-exports.md
> +Example of **correct** code for the `"restrictedNamedExportsPattern"` option:
```suggestion

:::

Example of **correct** code for the `"restrictedNamedExportsPattern"` option:
```

2024-05-11 11:56 UTC, Tanujkanti4441 commented on docs/src/rules/no-restricted-exports.md
>  ### restrictDefaultExports
```suggestion

:::

### restrictDefaultExports
```

need to close `correct` tag here

2024-05-11 11:56 UTC, Tanujkanti4441 commented on tests/lib/rules/no-restricted-exports.js
> +
can you also add an example with negation `!` pattern, like one given in the issue?

2024-05-12 13:24 UTC, mdjermanovic commented on lib/rules/no-restricted-exports.js
> +            let hasRestrictedNamePattern = false;
Can we rename this to `matchesRestrictedNamePattern`? I think it would be more clear what true/false means.

2024-05-12 13:37 UTC, mdjermanovic commented on lib/rules/no-restricted-exports.js
> +                hasRestrictedNamePattern = name && patternRegex.test(name);
```suggestion
                hasRestrictedNamePattern = patternRegex.test(name);
```

At this point, `name` is certainly a string, and a falsy empty string name should also be checked against the pattern.

```js
/*eslint no-restricted-exports: ["error", {
    "restrictedNamedExportsPattern": "^$"
}]*/


const foo = 1;

export { foo as "" }; // false negative, it matces the pattern

```

2024-05-12 16:23 UTC, mdjermanovic reviewed
Looks good, just we didn't discuss how this option would correlate with `restrictDefaultExports`. For example, when the pattern matches `"default"` but some default exports are explicitly allowed by `restrictDefaultExports`.

I think the best solution is that this option simply doesn't apply to `default` exports.

2024-05-12 16:23 UTC, mdjermanovic commented on docs/src/rules/no-restricted-exports.md
> +
```suggestion

Note that this option does not apply to `export default` or any `default` named exports. If you want to also restrict `default` exports, use the `restrictDefaultExports` option.
```

2024-05-12 16:23 UTC, mdjermanovic commented on lib/rules/no-restricted-exports.js
> +            if (restrictedNamePattern) {
```suggestion
            if (restrictedNamePattern && name !== "default") {
```

I think this is the only code change needed, but we should also add a few tests.

2024-05-13 10:37 UTC, mdjermanovic reviewed
A few more tests to confirm that this option doesn't apply to `default`.

2024-05-13 10:37 UTC, mdjermanovic commented on tests/lib/rules/no-restricted-exports.js
> +        },
```suggestion
        {
            code: "var foobar; export default foobar;",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "export default 'default';",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "var foobar; export { foobar as default };",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "var foobar; export { foobar as 'default' };",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "export { default } from 'mod';",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "export { default as default } from 'mod';",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "export { foobar as default } from 'mod';",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
        {
            code: "export * as default from 'mod';",
            options: [{ restrictedNamedExportsPattern: "default" }]
        },
```

2024-05-13 16:39 UTC, mdjermanovic approved these changes
LGTM, thanks! Leaving open for @Tanujkanti4441 to verify.

2024-05-14 06:32 UTC, Tanujkanti4441 approved these changes
LGTM, thanks for contributing!

2024-05-14 08:21 UTC, merged