docs: clarify func-style
eslint/eslint pull request #18477
Opened 2024-05-19 20:27 UTC by camsteffen

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

* Say "function expressions assigned to variables" in some cases for clarity
* Prefer `const` over `var` in examples
* Some tidying/rewording
* Add a note saying the lint does not apply to all functions

#### Is there anything you'd like reviewers to focus on?

2024-05-20 14:52 UTC, nzakas commented on docs/src/rules/func-style.md
> +const doSometing = () => {
Let's use unique IDs to avoid syntax errors.

```suggestion
const doSomethingElse = () => {
```

2024-05-22 12:57 UTC, Tanujkanti4441 commented
Hi @camsteffen, some requested changes are yet to be implemented, can you implement the rest also?

2024-05-22 13:27 UTC, camsteffen commented
*facepalm* I'm sorry, I had the changes locally but didn't actually push them up.

2024-05-24 11:31 UTC, snitin315 approved these changes
LGTM. I will leave it open for @nzakas

2024-05-25 20:21 UTC, mdjermanovic requested changes
We don't use the term "lint" for rules.

2024-05-25 20:21 UTC, mdjermanovic commented on docs/src/rules/func-style.md
> +Note: This lint does not apply to *all* functions. For example, a callback function passed as an argument to another function is not considered by this lint.
```suggestion
Note: This rule does not apply to *all* functions. For example, a callback function passed as an argument to another function is not considered by this rule.
```

2024-05-27 16:07 UTC, nzakas approved these changes
LGTM. I applied @mdjermanovic's suggestion, so this is good to go. Thanks!

2024-05-27 16:07 UTC, merged