docs/better `global ignores` instruction
eslint/eslint pull request #19297
Opened 2024-12-31 18:43 UTC by tresorama

#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] Documentation update
[ ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/HEAD/templates/rule-change-proposal.md))
[ ] Add autofix to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

#### What changes did you make? (Give an overview)

- explain that user must use `global ignores` features if he wants to ignore files/dir and control the definition in a single place
- added example

#### Is there anything you'd like reviewers to focus on?

This PR is not ready, due to:
- i'm still working on it
- In the text I updated, I used some assumption on some eslint behaviors that i'm not sure they are real. I need that a person who knows eslint internal review my text, specifically:
  - I wrote `Each configuration object of the array in eslint.cong.js is an independent configuration`. Is it true?

2025-01-01 14:26 UTC, Tanujkanti4441 commented
Hi @tresorama, thanks for the PR, can you also sign the CLA?

2025-01-01 14:28 UTC, Tanujkanti4441 requested changes

2025-01-01 14:28 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +
```suggestion
The usage is the following:
* define a configuration object with a single prop, `ignores` .
* **don't add any other props** to this configuration object, only `ignores` prop
* place this configuration objects as **first item** of the configuration object arrays

```

To fix the CI errors

2025-01-01 14:31 UTC, tresorama commented
> Hi @tresorama, thanks for the PR, can you also sign the CLA?

Sure, but I never did it.
I checked [this page](https://eslint.org/docs/latest/contribute#sign-the-cla) but i have no idea what I am supposed to do...
Could you guide me or reference an online resource ?

2025-01-01 14:49 UTC, tresorama commented
> You can head over to the following link and select and fill details according to your specifications.
> 
> https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/3d9a9c15-cb4a-478d-a185-d8d2881dd914/user/acb740db-7810-4839-a24b-204b15d23b7e?redirect=https:%2F%2Fgithub.com%2Feslint%2Feslint%2Fpull%2F19297
> 
Thanks, I'm filling it.
Do i need to upload my real "hand-drawn" sign or I can use the autogenerated one ? Does this makes a difference ?

> i think instead of replying i edited you post by mistake, sorry for that!
No problem at all

2025-01-01 14:52 UTC, Tanujkanti4441 commented
>Do i need to upload my real "hand-drawn" sign or I can use the autogenerated one ? Does this makes a difference ?
 
you can draw it.

2025-01-01 14:54 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +In the code above, the `ignores` directive of `config-1` is not applied on `config-2`, and vice-versa.  If this is what you want, use this pattern.
Is true this part ? 

I'm not sure that what i wrote it's true, this is my personal assumption based on my usage of eslint, but I'm not an expert in eslint.
I want to be sure to not create more confusion...

2025-01-01 14:57 UTC, tresorama commented
> you can draw it.

 Great! It finished the CLA.

2025-01-01 14:59 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +In the code above, the `ignores` directive of `config-1` is not applied on `config-2`, and vice-versa.  If this is what you want, use this pattern.
I'm referring specifically to 

> It's important to note that each configuration object, it's independent from other ones. Because of that, the `ignores` prop defined in one configuration object is not applied to other configuration objects of the array.


Configuration objects are independent?

2025-01-01 15:08 UTC, tresorama commented
CLA added, I found the correct button to press to init the process
<img width="892" alt="Schermata 2025-01-01 alle 16 06 03" src="https://github.com/user-attachments/assets/ff5bdfed-c388-414e-8574-2a24270785f0" />

Previously i clicked on the link you provided me and completed the CLA, but the form of the CLA was prefilled with your name. Please check that i'm not overwritten yours. @Tanujkanti4441

2025-01-02 07:32 UTC, Tanujkanti4441 commented
> Previously i clicked on the link you provided me and completed the CLA, but the form of the CLA was prefilled with your name. Please check that i'm not overwritten yours. @Tanujkanti4441

Thanks for sharing, i have deleted the posts with that link, hope that's okay.

2025-01-02 08:55 UTC, Tanujkanti4441 commented on docs/src/use/configure/configuration-files.md
> +* `ignores` - An array of glob patterns indicating the files that the configuration object should not apply to. If not specified, the configuration object applies to all files matched by `files`. [gl
```suggestion
* `ignores` - An array of glob patterns indicating the files that the configuration object should not apply to. If not specified, the configuration object applies to all files matched by `files`. If `ignores` is used without any other keys in the configuration object, then the patterns act as [global ignores](#globally-ignoring-files-with-ignores) and it gets apply to every configuration object.
```

I think this much modification is good?

2025-01-02 08:55 UTC, Tanujkanti4441 commented on docs/src/use/configure/configuration-files.md
>  If `ignores` is used without any other keys in the configuration object, then the patterns act as global ignores. Here's an example:
```suggestion
If `ignores` is used without any other keys in the configuration object, then the patterns act as global ignores. This way it gets apply to every configuration object. While patterns in non-global `ignores` only match the files or files within directories, patterns in global `ignores` can also match directories. Here's an example:
```

Let's try to match this with above description a bit.

2025-01-02 09:18 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +It's important to note that each configuration object, it's independent from other ones. Because of that, the `ignores` prop defined in one configuration object is not applied to other configuration
```suggestion
In ESLint, there is a concept of global `ignores`, to better explain it let's see first how configuration object works in ESLint.

ESLint configuration file is intended to be used like this: export a single array, that contains multiple [configuration objects](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects), each one being an item of the array.  

It's important to note that each configuration object is independent from other ones. Because of that, the `ignores` property defined in one configuration object is not applied to other configuration objects of the array.
```

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +];
```suggestion
export default [
    { name: "config-1", files: "src/**/*.js", ignores: ["**/*.config.js"], ... }, 
    { name: "config-2", files: "scripts/**/*.js", ignores: ["**/dir/**"], ... }, 
    // ...
];
```

Here we can show that `config-1` is ignoring a file and `config-2` is ignoring files inside a directory.

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +In the code above, the `ignores` directive of `config-1` is not applied on `config-2`, and vice-versa.  If this is what you want, use this pattern.
Yes they are.

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +But usually, what you want is to globally ignores some directory/files, and apply this directive to all configuration objects of the array:  `global ignores` is exactly made for this scenario.
```suggestion
But if you want to apply a particular `ignores` pattern to all configuration objects of the configuration array,  global `ignores` is exactly made for this scenario.
```

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +* place this configuration objects as **first item** of the configuration object arrays
```suggestion
* define a configuration object with a single property, `ignores` .
* **don't add any other property** to this configuration object other than `ignores` property.
* place this configuration object as **first item** of the configuration array.
```

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +This way every configuration object that follow this one inherit the `global ignores`.
```suggestion
This way every configuration object that follow this one inherit the global `ignores`.
```

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +```ts
```suggestion

```js
```

Let's keep it a `js` example

2025-01-02 09:44 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +];
```suggestion
// eslint.config.js

import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  // DO NOT PUT OTHER PROPS IN THIS OBJECT, SO IT
  // BEHAVES AS GLOBAL IGNORES
  { ignores: ["**/node_modules/**", "dist/"] }, 

  // THE IGNORES IS APPLIED ALSO TO THESE FOLLOWING CONFIGS
  { files: ["**/*.{js,mjs,cjs,ts}"] },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

2025-01-02 09:46 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +In the code above, the `ignores` directive of `config-1` is not applied on `config-2`, and vice-versa.  If this is what you want, use this pattern.
yes they are.

2025-01-02 16:29 UTC, tresorama commented on docs/src/use/configure/configuration-files.md
>  If `ignores` is used without any other keys in the configuration object, then the patterns act as global ignores. Here's an example:
I made a big-rewrite of this section in https://github.com/eslint/eslint/pull/19297/commits/c6efc5197988afd344f6e54d788c8a4c7c4d1f48, check that

2025-01-02 16:38 UTC, tresorama commented
I quote myself from the PR description
> Out of the scope of this PR but useful
>
> I think that we should merge all section of documentation that explain "ignoring files and directory" to a same page.
Now user need to read both [Configuration Files](https://eslint.org/docs/latest/use/configure/configuration-files#excluding-files-with-ignores) and [Ignore](https://eslint.org/docs/latest/use/configure/ignore) page.
Having a single page instead of multiple ones would simplify "links" from other pages of the docs, and avoid duplicating docs updates.


What if we tackle this problem in this PR ? Or in a new one ? @Tanujkanti4441 

There is a lot duplication of `ignores` usage description between the two pages.
I would remove everything related to `ignores` from [Configuration Files](https://eslint.org/docs/latest/use/configure/configuration-files#excluding-files-with-ignores) and move to [Ignore](https://eslint.org/docs/latest/use/configure/ignore)

2025-01-02 18:12 UTC, nzakas reviewed
Thanks for working on this. The new content on the configuration files page is excellent, very well done. I just left some suggestions for cleaning things up.

I don't think the new content on the ignores page flows with the rest of the content. Please see my comment inline for that.

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* `ignores` - An array of glob patterns indicating the files that the configuration object should not apply to. If not specified, the configuration object applies to all files matched by `files`. If
```suggestion
* `ignores` - An array of glob patterns indicating the files that the configuration object should not apply to. If not specified, the configuration object applies to all files matched by `files`. If `ignores` is used without any other keys in the configuration object, then the patterns act as [global ignores](#globally-ignoring-files-with-ignores) and it gets applied to every configuration object.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* If `ignores` is used without any other keys in the configuration object, then the patterns act as global ignores. This way it gets apply to every configuration object (not only to the configration
```suggestion
* When `ignores` is used without any other keys (besides `name`) in the configuration object, then the patterns act as global ignores. This means they apply to every configuration object (not only to the configuration object in which it is defined). Global `ignores` allows you not to have to copy and keep the `ignores` property synchronized in more than one configuration object.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* If `ignores` is used in conjunction with other properties in the same configuration object, then the patterns act as non-global ignores. This way `ignores` applies only that configuration object
```suggestion
* If `ignores` is used with other properties in the same configuration object, then the patterns act as non-global ignores. This way `ignores` applies only to the configuration object in which it is defined.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* patterns in global `ignores` can also match directories (`dir/`), other than files like "non-global".
```suggestion
* patterns in global `ignores` can match directories (`dir/`) in addition to the patterns that non-global ignores supports.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +In any case (non-global or global):
```suggestion
For all uses of `ignores`:
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* the glob patterns you define are added after the default patterns, which are `["**/node_modules/", ".git/"]`
```suggestion
* The patterns you define are added after the default ESLint patterns, which are `["**/node_modules/", ".git/"]`.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/configuration-files.md
> +* glob patterns always match files and directories that begin with a dot, such as `.foo.js` or `.fixtures`, unless those files are explicitly ignored. The only dot directory ignored by default is `.g
```suggestion
* The patterns always match files and directories that begin with a dot, such as `.foo.js` or `.fixtures`, unless those files are explicitly ignored. The only dot directory ignored by default is `.git`.
```

2025-01-02 18:12 UTC, nzakas commented on docs/src/use/configure/ignore.md
> +## Global Ignores
This section seems out of place with the rest of the content on this page. The entire page is about ignoring files and directories using global ignores, so it doesn't make sense to have a separate section.

I also feel like some of this content is redundant to what's on the configuration files page.

I'd much rather see some of this content distributed throughout this page in the existing sections rather than putting in an entirely new block that duplicates some of the content.

2025-01-02 19:25 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +## Global Ignores
Yeah! There is a lot of ambiguities between these two pages.

Personally, if I start reading [Ignore](https://deploy-preview-19297--docs-eslint.netlify.app/use/configure/ignore) page I don't think this page is related to "global" only configuration of ignores. But to "ignores" in general.

For me the simpler approach for the reader is to have:
 - [Configuration Files](https://deploy-preview-19297--docs-eslint.netlify.app/use/configure/configuration-files#configuration-objects) page with a brief description of every properties of configuration object, with links to other pages if that property need big explanation (like ignores) <img width="400" alt="Schermata 2025-01-02 alle 20 14 29" src="https://github.com/user-attachments/assets/4e75651b-278e-4c04-a7f7-76d7608d0d53" />
- move all these subsections related to ignores from **Configuration Files** page to **Ignores** page <img width="157" alt="Schermata 2025-01-02 alle 20 18 43" src="https://github.com/user-attachments/assets/46f6c1b9-4be5-4c02-9aa8-b759390cc60f" />
- remove redundancy and refactor sections of **Ignores** page due to big amount of information


This is not an easy task, this is why i marked this as **Out of scpoe of this PR**.
What do you think ? @nzakas @Tanujkanti4441

2025-01-03 17:46 UTC, nzakas commented on docs/src/use/configure/ignore.md
> +## Global Ignores
I agree that we don't want to completely reorganize the documentation for this PR. There are a lot of links to different sections that would need to be verified to avoid breaks, so I think for this PR we want to focus on building out content within the current structure.

2025-01-03 17:52 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +## Global Ignores
Great! 
Do you have an idea of how to proceed?

I haven't an idea of how to refactor this piece of text (the one attached to this comment )

2025-01-03 17:58 UTC, nzakas commented on docs/src/use/configure/ignore.md
> +## Global Ignores
I don't have the time to look into that right now. To move forward, I'd suggest just reverting the changes to `ignore.md` so we can merge the rest of this PR. We can revisit additional changes later.

2025-01-07 19:44 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +## Global Ignores
I agree!

Changes made:

- in https://github.com/eslint/eslint/pull/19297/commits/00b058504034df2d48089ebcc664f8fe87b655ba : 
reverted all changes to `ignore.md`, now the ignore page is at the same state "before this PR"
- in https://github.com/eslint/eslint/pull/19297/commits/00b058504034df2d48089ebcc664f8fe87b655ba : 
[Live Preview](https://deploy-preview-19297--docs-eslint.netlify.app/use/configure/ignore)
To inform the user who arrives on `ignore.md` page without having gone through `configuration-files.md` (where we explain the difference between global and non-global ignores) I added a `tip/alert` at the top of `ignore.md` page, hoping the user will read it before going through the `ignore.md` page. <img width="540" alt="Schermata 2025-01-07 alle 20 30 22" src="https://github.com/user-attachments/assets/a235421c-4b9b-4bf1-80d3-8b2c1635f1e1" />

**Please check english syntax/grammar of this tip/alert**, I'm not a native english speaker

2025-01-08 09:43 UTC, Tanujkanti4441 commented on docs/src/use/configure/ignore.md
> +
```suggestion
::: tip
The `ignores` property in ESLint configuration object can behave as global or non-global, based on how you use it. Please read how [ignores can be used as global or non-global](configuration-files#globally-ignoring-files-with-ignores) before going through this page.
:::

```

first sentence seems repetitive, how about if we write something like this?

2025-01-08 16:33 UTC, tresorama commented
I think we are at merging point. 
In last commit the browser test is failed, but I think is a random initialization error of the Github Action machine, that will disappear with a new commit.

Please approve me if everything is allrights by your side,so I will do the last step, merging `main` into this branch.
@nzakas @Tanujkanti4441

2025-01-08 17:11 UTC, nzakas commented on docs/src/use/configure/ignore.md
> +This page explains how to use `ignores` property of an ESLint configuration object. The `ignores` property can behave as global or non-global, based on how you use it. Please read how [ignores can be
```suggestion
This page explains how to use `ignores` property of an ESLint configuration object to globally ignore files and directories. The `ignores` property can behave as either global or non-global depending on how you use it. For more information on non-global ignores, see [Specifying files and ignores](configuration-files#specifying-files-and-ignores).
```

2025-01-08 17:55 UTC, tresorama commented on docs/src/use/configure/ignore.md
> +This page explains how to use `ignores` property of an ESLint configuration object. The `ignores` property can behave as global or non-global, based on how you use it. Please read how [ignores can be
Added in https://github.com/eslint/eslint/pull/19297/commits/45ae8059c9807d02a53f471f1bc9a47b38c63997 with an additional line.

2025-01-08 17:59 UTC, tresorama commented
in https://github.com/eslint/eslint/pull/19297/commits/8b895df556ac5d61b7efba8104ff91ac6f166beb , just for demonstration I renamed the `Ignores Files` page to `Global Ignores`, to see how it would look like. It changes the left sidebar nav item and also the page title.

Let me know if we want to discard or not this change in this PR @nzakas

2025-01-12 00:17 UTC, tresorama commented
Reverted last commit, so we can merge with already accepted state

2025-01-12 16:25 UTC, Tanujkanti4441 approved these changes
LGTM. Thanks!

Would like another team member to review this.

2025-01-13 17:22 UTC, mdjermanovic commented on docs/src/use/configure/configuration-files.md
> +* When `ignores` is used without any other keys (besides `name`) in the configuration object, then the patterns act as global ignores. This means they apply to every configuration object (not only to
I think the "global ignores apply to every configuration object" point of view is confusing as it implies a relation between global and non-global ignores, e.g., that non-global ignores can unignore files ignored by global ignores or vice versa, which isn't the case. I think we should keep global and non-global ignores described as two separate concepts:

1. Global ignores specify which files should be entirely ignored.
2. Non-global ignores specify which files the config object should not apply to.

2025-01-13 19:54 UTC, tresorama commented on docs/src/use/configure/configuration-files.md
> +* When `ignores` is used without any other keys (besides `name`) in the configuration object, then the patterns act as global ignores. This means they apply to every configuration object (not only to
I'm not sure if I understood this correctly, and I don't know the internals.

Let's create an example to tackle this...

```js
// eslint.config.js

// Mix global and non-global ignores
export default [
    {
      name: "global-ignores",
      ignores: [".config/", "dist/", "tsconfig.json"]
      // This globally ignores ".config/", "dist/", "tsconfig.json"
    },
    {
      name: "non-global-ignores-1",
      ignores: [".eslint.config.js"],
      rules: {... }
      // This inherits globally ignores of ".config/", "dist/", "tsconfig.json"
      // and also ignore (only for this config object) ".eslint.config.js"
    },
];
```

Is this correct ?


> that non-global ignores can unignore files ignored by global ignores

Can you create a code example (like the one above) that does that ?

2025-01-13 21:25 UTC, nzakas commented
I don't think renaming "Ignore Files" to "Global Ignores" makes sense. "Ignore Files" is something people will understand even if they're completely new to ESLint; "Global Ignores" is an ESLint-specific concept that I think hides the actual intent.

2025-01-13 22:47 UTC, tresorama commented
If you following the Getting Started tutorial in a typescript project, you do this


**1. Install Eslint**
 
```
npm init @eslint/config@latest
```
and answer this to the wizard:
```
@eslint/create-config: v1.4.0

✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · typescript
✔ Where does your code run? · browser
The config that you've selected requires the following dependencies:

eslint, globals, @eslint/js, typescript-eslint
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
☕️Installing...
```

This is the `eslint.config.js` you get:
```js
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";


/** @type {import('eslint').Linter.Config[]} */
export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

**2. Ignore files**

Then, if you would ignore all compiled files (`dist` dir), without looking at the docs, you likely modify the config like so:

```diff
/** @type {import('eslint').Linter.Config[]} */
export default [
- { files: ["**/*.{js,mjs,cjs,ts}"]},
+ { files: ["**/*.{js,mjs,cjs,ts}"], ignores : [ "dist/" ] },
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

But it's not working, eslint keep processing `dist` directory. You don't know why.
At this point you go to the docs website and look for explanation of ignores.


> On my first attempt, I was stuck here.
> The docs website is missing an explicit definition of `global` vs `non-global` ignores, so I  wasn't able to make the code working, so I started searching for issues on Github... that land me to https://github.com/eslint/eslint/discussions/18304


**3. Read the docs and fix code**

You read the docs and, after reading them, your mental model should be:
> eslint doesn't ignore the `dist` directory, because that config object uses `non-global` ignores. What I want is `global ignores`

Then you correct the code with:
```diff
/** @type {import('eslint').Linter.Config[]} */
export default [
+ { ignores : [ "dist/" ] },
  { files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
];
```

2025-01-14 16:09 UTC, tresorama commented
> ```js
> 
> /** @type {import('eslint').Linter.Config[]} */
> 
> export default [
> 
>  { files: ["**/*.{js,mjs,cjs,ts}"], ignores : [ "dist/" ] },
> 
>   {languageOptions: { globals: globals.browser }},
> 
>   pluginJs.configs.recommended,
> 
>   ...tseslint.configs.recommended,
> 
> ];
> 
> ```
> 
> 
> 
> let me clear this, first of all `dist/` pattern indicates a directory and for non-global ignores we have to use `dist/**` pattern.
> 
> 
> 
> Here `ignores` is not ignoring files because the rules that are applied by the eslint here are recommended rules (`pluginJs.configs.recommended`) and which are outside of this configuration object => `{ files: ["**/*.{js,mjs,cjs,ts}"], ignores : [ "dist/**" ] }` so in this config recommended rules will be applied to all the `js` and `ts` regardless of the `files` and `ignores` specified in the configuration object and in order to ignore the files from being linted we have to use global `ignores` here.
> 
> 
> 
> And `files` and `ignores` property in `{ files: ["**/*.{js,mjs,cjs,ts}"], ignores : [ "dist/**" ] }` config object will only work for the rules present inside it like:
> 
> 
> 
> ```js
> 
> export default [
> 
>  {
> 
>  files: ["**/*.{js,mjs,cjs,ts}"], 
> 
>  ignores : [ "dist/**" ],
> 
>  rules: { "no-unused-vars": "error }
> 
>   },
> 
> ];
> 
> ```
> 
> or to use recommended rules inside config object:
> 
> 
> 
> ```js
> 
> export default [
> 
>  {
> 
> files: ["**/*.{js,mjs,cjs,ts}"], 
> 
> ignores : [ "dist/**" ],
> 
> rules: {
> 
> ...pluginJs.configs.recommended.rules
> 
> }
> 
>  },
> 
> ];

Great description!
What you described is exactly what an user that read the docs should be able to explain to others, and the goal of this PR

The solution is to use global ignores , so the user should have the mental knowledge to do that.

We are really near the ideal "text" for me with this PR

2025-01-14 17:39 UTC, nzakas commented
@tresorama I understand your reasoning, and I disagree with your conclusion. I'd like the title of the page to still be "Ignore Files" as I think that's what most people will be looking for.

2025-01-15 09:23 UTC, tresorama commented
> @tresorama I understand your reasoning, and I disagree with your conclusion. I'd like the title of the page to still be "Ignore Files" as I think that's what most people will be looking for.

The title was reverted in https://github.com/eslint/eslint/pull/19297/commits/da9e945562d1930db266a1a5938638004545af71 . It was a short test to "see how it would look like" but that path requires a lot of changes so it's better to tackle it in a future PR.

So for this PR the current state is this:
- all changes are made on **Configuration Files** page
- only a `tip` is added on **Ignore Files** page

Live Preview: 
https://deploy-preview-19297--docs-eslint.netlify.app/

2025-01-15 16:58 UTC, mdjermanovic commented on docs/src/use/configure/configuration-files.md
> +* When `ignores` is used without any other keys (besides `name`) in the configuration object, then the patterns act as global ignores. This means they apply to every configuration object (not only to
> > that non-global ignores can unignore files ignored by global ignores
> 
> Can you create a code example (like the one above) that does that ?

It doesn't work, but it could be understood that a config like this would enable linting of `tsconfig.json`:

```js
// eslint.config.js

// Mix global and non-global ignores
export default [
    {
      name: "global-ignores",
      ignores: [".config/", "dist/", "tsconfig.json"]
      // This globally ignores ".config/", "dist/", "tsconfig.json"
    },
    {
      name: "non-global-ignores-1",
      ignores: ["!tsconfig.json"], // attempts to apply this config to tsconfig.json and enable its linting
      rules: {... }
    },
];
```

2025-01-15 17:38 UTC, tresorama commented on docs/src/use/configure/configuration-files.md
> +* When `ignores` is used without any other keys (besides `name`) in the configuration object, then the patterns act as global ignores. This means they apply to every configuration object (not only to
Clear!
 to discourage this pattern I would add a text in the section that explain the usage of "!pattern" if it is present in the docs.

If not present, this should be close to one of the first text that it's about "glob pattern" usage 

This can be a new PR

2025-01-16 15:08 UTC, mdjermanovic commented
I personally think this would make the docs about ignores more confusing. Global ignores do not apply to every configuration object but are a separate concept that specifies files that should be entirely ignored. Non-global ignores do not inherit global ignores, otherwise it would be expected that global and non-global ignores interact with each other and that it's possible for one to unignore the other, which isn't the case.

2025-01-16 21:45 UTC, nzakas commented
@mdjermanovic I think that, while not technically correct, this description is conceptually accurate. Fundamentally, you can think of global ignores as applying to every configuration object, because no rules or other settings will ever be applied. If your concern is that global ignores can't be unignored, I think that can easily be described by saying that global ignores are always applied after local ignores. 

At the end of the day, the goal of the docs is to help people understand what's happening rather than providing implementation details. I think this is an interesting way of doing this, and unless you have a better idea for improving the docs, I think it's worth putting this out and seeing if it helps. Worse case scenario, we can always revert in a later release or make updates to improve clarity.

2025-01-17 11:30 UTC, mdjermanovic approved these changes
LGTM, thanks!

2025-01-17 11:31 UTC, merged

2025-01-17 19:21 UTC, tresorama commented
Great work, thanks guys! @nzakas @mdjermanovic @nzakas 

I would suggest to keep the issue https://github.com/eslint/eslint/discussions/18304 opened (or closed but with enabled comments) for a while as a metric of success of this PR. If the docs changes made by this PR are enough for user-land we should note that nobody reply to that issue anymore because the docs did its job. If instead, people reply, we have a concrete signal that finetuning its needed.